version: 2

models:
  - name: zendesk_problems
    columns:
        - name: ticket_id
          tests:
              - unique
              - not_null

  - name: zendesk_incidents
    columns:
        - name: ticket_id
          tests:
              - unique
              - not_null

  - name: zendesk_problems_w_incident_detail
    columns:
        - name: problem_id
          tests:
              - not_null
              - unique
        - name: subject
          tests:
              - not_null
        - name: last_reported_at
          tests:
              - not_null

  - name: zendesk_incidents_w_problem_detail
    columns:
        - name: incident_id
          tests:
              - not_null
              - unique
        - name: problem_id
          tests:
              - not_null
        - name: reported_at
          tests:
              - not_null

  - name: zendesk_links_current
    columns:
        - name: problem_id
          tests:
              - not_null
              - unique

  - name: zendesk_tickets_tagged
    columns:
        - name: ticket_id
          tests:
              - not_null
              - unique

  - name: zendesk_tickets_detailed
    columns:
        - name: ticket_id
          tests:
              - not_null
              - unique

  - name: zendesk_ticket_metrics_support
    columns:
        - name: ticket_id
          tests:
              - not_null
              - unique
