version: 2

models:
  - name: product_bugs
    columns:
        - name: title
          tests:
              - not_null
        - name: created_at
          tests:
              - not_null

  - name: product_bugs_daily
    columns:
        - name: date
          tests:
              - unique
              - not_null
        - name: all_bugs
          tests:
              - not_null

  - name: product_failure_rate
    columns:
        - name: all_bugs
          tests:
              - not_null
        - name: deploys_count
          tests:
              - not_null

  - name: product_mean_time_to_resolve
    columns:
        - name: issue_id
          tests:
              - not_null
              - unique
        - name: time_to_resolve_working_min
          tests:
              - not_null
        - name: time_to_resolve_working_days
          tests:
              - not_null

  - name: product_open_problems
    columns:
        - name: date_day
          tests:
              - not_null
              - unique
        - name: p1_bugs
          tests:
              - not_null
        - name: p2_bugs
          tests:
              - not_null
        - name: p3_bugs
          tests:
              - not_null
        - name: all_bugs
          tests:
              - not_null
