version: 2

models:
  - name: product_bugs
    columns:
        - name: title
          tests:
              - not_null
        - name: created_at
          tests:
              - not_null

  - name: product_bugs_daily
    columns:
        - name: date
          tests:
              - unique
              - not_null
        - name: all_bugs
          tests:
              - not_null

  - name: product_failure_rate
    columns:
        - name: all_bugs
          tests:
              - not_null
        - name: deploys_count
          tests:
              - not_null

  - name: product_star_rating
    columns:
        - name: episode_id
          tests:
              - not_null
        - name: rating
          tests:
              - not_null
              - accepted_values:
                  values: [0, 1, 2, 3, 4, 5]
    tests:
      - unique:
          column_name: "concat(episode_id, contract_id)"

  - name: product_mean_time_to_resolve
    columns:
        - name: date_week
          tests:
              - not_null
              - unique
        - name: p1_bugs_count
          tests:
              - not_null
        - name: p2_bugs_count
          tests:
              - not_null

  - name: product_open_problems
    columns:
        - name: date_day
          tests:
              - not_null
              - unique
        - name: p1_bugs
          tests:
              - not_null
        - name: p2_bugs
          tests:
              - not_null
        - name: p3_bugs
          tests:
              - not_null
        - name: all_bugs
          tests:
              - not_null

  - name: product_login_rate
    columns:
        - name: date_day
          tests:
              - not_null
              - unique
        - name: login
          tests:
              - not_null
        - name: fraction
          tests:
              - not_null

  - name: product_find_rate
    description: a model for comparing how many bugs are found by tech
      compared to by our users
    columns:
        - name: date_day
          tests:
              - unique
              - not_null
