
version: 2

models:
  - name: unresponsive_episode_set_unresponsive_daily
    columns:
      - name: episode_id
        tests:
          - not_null
      - name: date_day_est
        tests:
          - not_null
    tests:
      - unique:
          column_name: "concat(date_day_est, episode_id)"
