
# Name your package! Package names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models

name: 'dialogue'
version: '1.0'

# This setting configures which "profile" dbt uses for this project. Profiles contain
# database connection information, and should be configured in the  ~/.dbt/profiles.yml file
profile: 'dialogue'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that source models can be found
# in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"] 
test-paths: ["tests", "models/xero/tests", "models/salesforce/tests",
  "models/scribe/tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

quoting:
  identifier: false
  schema: false

# You can define configurations for models in the `source-paths` directory here.
# Using these configurations, you can enable or disable models, change how they
# are materialized, and more!

# In this example config, we tell dbt to build all models in the example/ directory
# as views (the default). Try changing `view` to `table` below, then re-running dbt
models:
  dialogue:
      # Send a timestamp for all models create and complete to analytics_audit
      pre-hook:
        - "create table if not exists {{this.schema}}_audit.dbt_audit_log (
            event_name text,
            event_timestamp timestamp,
            event_schema text,
            event_model text,
            invocation_id text
        )"
        - "insert into {{this.schema}}_audit.dbt_audit_log (
            event_name,
            event_timestamp,
            event_schema,
            event_model,
            invocation_id
          ) values (
            'starting model run',
            clock_timestamp(),
            '{{this.schema}}',
            '{{this.name}}',
            '{{ invocation_id }}'
        )"
      post-hook:
        - "insert into {{this.schema}}_audit.dbt_audit_log (
            event_name,
            event_timestamp,
            event_schema,
            event_model,
            invocation_id
          ) values (
            'completed model run',
            clock_timestamp(),
            '{{this.schema}}',
            '{{this.name}}',
            '{{ invocation_id }}'
        )"
      coredata:
          materialized: table
      dimension:
          materialized: ephemeral
      github:
          materialized: table
      messaging:
          transform:
              materialized: view
      meta:
          materialized: table
      scribe:
          materialized: table
      tableau:
          materialized: table
      usher:
          materialized: table
      wiw:
          materialized: table
      xero:
          materialized: table

archive:
    - source_schema: analytics
      target_schema: archive
      tables:
        - source_table: nps_patient_list
          target_table: nps_patient_list_archived
          updated_at: timestamp
          unique_key: concat(user_id, timestamp)

    - source_schema: analytics
      target_schema: archive
      tables:
        - source_table: nps_dm_list
          target_table: nps_dm_list_archived
          updated_at: timestamp
          unique_key: concat(email, timestamp)
