
version: 2

models:
  - name: scribe_contracts
    columns:
      - name: contract_id
        tests:
          - not_null
          - unique

      - name: during
        tests:
          - not_null

      - name: organization_id
        tests:
          - not_null

      - name: created
        tests:
          - not_null

      - name: plan_id
        tests:
          - not_null

      - name: participant_id
        tests:
          - not_null

  - name: scribe_organizations
    columns:
      - name: organization_id
        tests:
          - not_null
          - unique

      - name: organization_name
        tests:
          - not_null

      - name: billing_start_date
        tests:
          - not_null

  - name: scribe_test_organizations
    description: Test organizations to exclude from analysis, such as churn,
      activation, and sign up. These exist in prod to allow QA to test in prod
      conditions.
    columns:
      - name: organization_id
        test:
          - not_null

  - name: scribe_users
    columns:
      - name: user_id
        tests:
          - not_null
          - unique

      - name: created_at
        tests:
          - not_null

      - name: status
        tests:
          - not_null
          - accepted_values:
              values: ['future', 'deleted', 'deactivated',
              'registered', 'invited']

      - name: language
        tests:
          - not_null
          - accepted_values:
              values: ['FR', 'EN', 'N/A']

      - name: gender
        tests:
          - not_null
          - accepted_values:
              values: ['M', 'F', 'N/A']

  - name: scribe_plans
    columns:
      - name: plan_id
        tests:
          - not_null
          - unique

      - name: charge_strategy
        tests:
          - not_null
          - accepted_values:
              values: ['free', 'auto_dynamic', 'dynamic', 'fixed']

      - name: charge_price
        tests:
          - not_null

      - name: organization_id
        tests:
          - not_null

  - name: scribe_user_contract
    columns:
      - name: user_id
        tests:
          - not_null

      - name: contract_id
        tests:
          - not_null

    tests:
      - unique:
          column_name: "concat(user_id, contract_id)"

  - name: scribe_child_added
    columns:
      - name: child_id
        tests:
          - not_null
          - unique

      - name: user_id
        tests:
          - not_null

      - name: timestamp
        tests:
          - not_null

  - name: scribe_tracks
    columns:
      - name: timestamp
        tests:
          - not_null

    tests:
      - dbt_utils.recency:
          field: timestamp
          datepart: hour
          interval: 15

  - name: scribe_administrator
    description: |
      Manual import from scribe DB on December 2nd 2018

  - name: scribe_feature
    description: |
      Manual import from scribe DB on December 2nd 2018

  - name: scribe_organization_administrator
    description: |
      Manual import from scribe DB on December 2nd 2018

  - name: scribe_plan_feature
    description: |
      Manual import from scribe DB on December 2nd 2018
