
version: 2

models:
  - name: wiw_costs_by_position_daily

    columns:
        - name: start_date
          tests:
              - not_null
        - name: position_name
          tests:
              - not_null
        - name: cost
          tests:
              - not_null
    tests:
      - unique:
          column_name: "concat(start_date, position_name)"

  - name: wiw_fte_monthly
    description: |
      Monthly number of full-time equivalent employees on the virtual care platform

    columns:
      - name: start_month
        tests:
          - not_null
          - unique

      - name: ftes
        tests:
          - not_null

  - name: wiw_costs_weekly
    columns:
      - name: start_week
        tests:
          - not_null
          - unique

      - name: virtual_costs_fl
        tests:
          - not_null

      - name: virtual_video_costs_fl
        tests:
          - not_null

      - name: virtual_chat_costs_fl
        tests:
          - not_null

      - name: virtual_costs_gp_fl
        tests:
          - not_null

      - name: virtual_costs_np_fl
        tests:
          - not_null

      - name: virtual_costs_nc_fl
        tests:
          - not_null

      - name: virtual_costs_cc_fl
        tests:
          - not_null
