
version: 2

models:
  - name: messaging_posts
    columns:
      - name: created_at
        tests:
          - not_null

    tests:
      - dbt_utils.recency:
          field: created_at
          datepart: hour
          interval: 15

  - name: messaging_dxa_cc
    columns:
      - name: episode_id
        tests:
          - not_null
      - name: timestamp
        tests:
          - not_null
      - name: cc
        tests:
          - not_null
