version: 2

models:
  - name: gm_by_account_monthly
    description: analyze GM on a monthly basis by account
    columns:
        - name: date_month
          tests:
              - not_null
        - name: gm_id
          description: a unique identifier for organization, province, month
          tests:
              - not_null
              - unique

  - name: gm_weekly
    columns:
        - name: date_week
          tests:
              - not_null
              - unique
