
version: 2

models:
  - name: dimension_dxa_chief_complaints
    columns:
      - name: chief_complaint
        tests:
          - not_null
          - unique

      - name: description_fr
        tests:
          - not_null
          - unique

      - name: description_en
        tests:
          - not_null
          - unique

  - name: dimension_weeks_saturday_start
    description: a dimension model of weeks with Saturday as the start date.
      These are used in the product_mean_time_to_resolve model.
    columns: 
      - name: date_week
        tests:
          - not_null
          - unique
    
  - name: dimension_days
    columns:
      - name: date_day
        tests:
          - not_null
          - unique

      - name: days_in_month
        tests:
          - not_null

  - name: dimension_months
    columns:
      - name: date_month
        tests:
          - not_null
          - unique

  - name: dimension_scorecard_weeks
    columns:
      - name: date_week
        tests:
          - not_null
          - unique

  - name: dimension_working_minutes
    columns:
      - name: date_minute
        tests:
          - not_null
          - unique

  - name: dimension_careplatform_reduced_hours
    description: |
      Dates when the service hours are reduced to 10:00 to 16:00
    columns:
      - name: date_day
        tests:
          - not_null
          - unique
