
version: 2

models:
  - name: assigned_time
    columns:
      - name: assignment_id
        tests:
          - not_null
          - unique
      - name: episode_id
        tests:
          - not_null
      - name: assigned_at
        tests:
          - not_null

  - name: assigned_time_detailed
    columns:
      - name: assignment_id
        tests:
          - not_null
          - unique
      - name: episode_id
        tests:
          - not_null
      - name: assigned_at
        tests:
          - not_null
      - name: main_specialization
        tests:
          - not_null
      - name: assignment_type
        tests:
          - not_null

  - name: assigned_time_w_posts
    columns:
      - name: assignment_id
        tests:
          - not_null
          - unique
      - name: episode_id
        tests:
          - not_null
      - name: assigned_at
        tests:
          - not_null
      - name: main_specialization
        tests:
          - not_null
      - name: count_posts
        tests:
          - not_null

  - name: chats
    columns:
      - name: chat_id
        description: |
          Hash of episode id and chat date
        tests:
          - not_null
          - unique
      - name: episode_id
        tests:
          - not_null
      - name: date_day_est
        tests:
          - not_null
      - name: initiator
        tests:
          - not_null
      - name: has_open_reminder
        tests:
          - not_null
      - name: set_resolved_pending
        tests:
          - not_null
      - name: chat_type
        tests:
          - not_null

  - name: chats_detailed
    columns:
      - name: episode_id
        tests:
          - not_null
      - name: date_day_est
        tests:
          - not_null
      - name: initiator
        tests:
          - not_null
      - name: has_open_reminder
        tests:
          - not_null
      - name: set_resolved_pending
        tests:
          - not_null
      - name: chat_type
        tests:
          - not_null
      - name: account_id
        tests:
          - not_null
      - name: account_name
        tests:
          - not_null
      - name: organization_id
        tests:
          - not_null
      - name: organization_name
        tests:
          - not_null
      - name: residence_province
        tests:
          - not_null

  - name: organizations
    columns:
      - name: organization_id
        tests:
          - not_null
          - unique
      - name: organization_name
        tests:
          - not_null
      - name: account_id
        tests:
          - not_null
      - name: account_name
        tests:
          - not_null
      - name: account_industry
        tests:
          - not_null
      - name: features
        tests:
          - not_null
      - name: has_mental_health
        tests:
          - not_null
          - accepted_values:
              values: [true, false]
      - name: has_24_7
        tests:
          - not_null
          - accepted_values:
              values: [true, false]

  - name: organizations_monthly
    columns:
      - name: date_month
        tests:
          - not_null
      - name: organization_id
        tests:
          - not_null
      - name: organization_name
        tests:
          - not_null
    tests:
      - unique:
          column_name: "concat(date_month, organization_id)"
      - dbt_utils.recency:
          field: date_month
          datepart: month
          interval: 1

  - name: accounts_monthly
    columns:
      - name: date_month
        tests:
          - not_null
      - name: account_id
        tests:
          - not_null
      - name: account_name
        tests:
          - not_null
      - name: mom_variation_type
        tests:
          - not_null
          - accepted_values:
              values: ['Expansion', 'Contraction', 'Stable', 'New', 'Churned']
    tests:
      - unique:
          column_name: "concat(date_month, account_id)"
      - dbt_utils.recency:
          field: date_month
          datepart: month
          interval: 1

  - name: active_users_unfiltered
    columns:
      - name: dau_id
        tests:
          - not_null
      - name: patient_id
        tests:
          - not_null
      - name: organization_id
        tests:
          - not_null
      - name: contract_id
        tests:
          - not_null
      - name: date_day
        tests:
          - not_null
      - name: family_member_type
        tests:
          - not_null
          - accepted_values:
              values: ['Employee', 'Dependent', 'Child']
    tests:
      - unique:
          column_name: "concat(date_day, patient_id, contract_id)"

  - name: active_users
    columns:
      - name: dau_id
        tests:
          - not_null
      - name: patient_id
        tests:
          - not_null
      - name: organization_id
        tests:
          - not_null
      - name: contract_id
        tests:
          - not_null
      - name: date_day
        tests:
          - not_null
      - name: set_active
        tests:
          - not_null
      - name: family_member_type
        tests:
          - not_null
          - accepted_values:
              values: ['Employee', 'Dependent', 'Child']
    tests:
      - unique:
          column_name: "concat(date_day, patient_id, contract_id)"

  - name: active_users_weekly
    columns:
      - name: date_week
        tests:
          - not_null
          - unique
      - name: waus
        tests:
          - not_null
      - name: daus
        tests:
          - not_null
      - name: daus_chat
        tests:
          - not_null
      - name: daus_video_gp_np
        tests:
          - not_null
      - name: waus_paid
        tests:
          - not_null
      - name: daus_paid
        tests:
          - not_null
      - name: daus_chat_paid
        tests:
          - not_null

  - name: active_users_monthly
    columns:
      - name: date_month
        tests:
          - not_null
          - unique
      - name: maus
        tests:
          - not_null
      - name: daus
        tests:
          - not_null
      - name: daus_chat
        tests:
          - not_null
      - name: daus_video_gp_np
        tests:
          - not_null
      - name: maus_paid
        tests:
          - not_null
      - name: daus_paid
        tests:
          - not_null
      - name: daus_chat_paid
        tests:
          - not_null
      - name: daus_video_gp_np_paid
        tests:
          - not_null

  - name: episodes
    description: A table containing unique episodes with details for analysis;
      in episodes_with_contracts these are then joined to get organization
      details but because of the possibility of having two active contracts
      this model is kept separate to allow for testing and analysis on unique
      episodes

    columns:
        - name: episode_id
          description: This is a unique identifier for the episode
          tests:
              - unique
              - not_null
        - name: user_id
          tests:
              - not_null
        - name: patient_id
          tests:
              - not_null
        - name: issue_type
          tests:
              - relationships:
                  to: ref('medops_issue_type_labels')
                  field: issue_type
        - name: triage_outcome
          description: |
            Triage groups used by post-DXA recommendation
          tests:
              - not_null
              - accepted_values:
                  values: ['treated_at_ubisoft_clinic', 'treated_by_gp',
                    'treated_by_np', 'treated_by_nurse', 'referral_er',
                    'referral_walk_in', 'navigation', 'other', 'N/A'
                  ]
        - name: treatment_category
          description: |
            The treatment category is a grouping of episodes by whom they were
            treated and for what; this is for analyzing usage of human
            resources and intake time across these groupings
          tests:
              - not_null
              - accepted_values:
                  values: ['N/A', 'other', 'treated_by_nurse', 'treated_by_np_gp',
                    'outreferred', 'treated_by_nc']
        - name: intake_time_first_patient_message
          description: |
            Intake time is an approximation of the time it takes to
            see the correct resource for the given reason for consultation;
            after this point it is assumed triage is complete and the
            consultation is starting.

            1) for an NP or GP video this is up to the least of appointment
            booking, the last message from the last nurse, and the first
            resolve of the episode;
            2) for navigation this is up to the lesser of the last message of
            the last nurse and the first resolve of the episode;
            3) for diagnostic without video this is up to the lesser of the
            first message from the last nurse or the first resolve of the
            episode.

            These timestamps are then compared with the first_patient_message
            to compute the time.
        - name: intake_time_first_set_active
          description: |
            The same as the above intake time definition; the timestamps are
            compared with the first_set_active to compute the time.
        - name: episode_type
          description: |
            Breakdown of episode by type of consultation

              PSY: Episodes categorized as Mental health and SMWB
              GP: Episodes including a GP consultation
              NP: Episodes including a NP consultation
              Out-referred: Episodes resolved with the following reasons:
              Referral without navigation, Referral walk in, Referral ER, Navigation
              NC: Episode does not fall in the categories above and includes an
              interaction with a nurse.
              Unsuitable episode: Episodes resolved with the following reasons:
              patient unresponsive, inappropriate profile, patient thanks,
              closed after follow up, follow up, international consult,
              episode duplicate, new dependant or resolved as other without
              falling into any category above

          tests:
              - not_null
              - accepted_values:
                  values: ['PSY', 'GP', 'NP', 'NP', 'Out-refered', 'NC',
                    'Unsuitable episode']

    tests:
      - dbt_utils.recency:
          field: created_at
          datepart: day
          interval: 1
      - dbt_utils.expression_is_true:
          expression: "intake_time_first_set_active > 0"
      - dbt_utils.expression_is_true:
          expression: "intake_time_first_patient_message > 0"
      # Calibrated in April 2019
      - dbt_utils.expression_is_true:
          expression: |
            saas_cost between .2 and .8
            or date_day_est < '2019-01-01'

  - name: accounts
    columns:
      - name: account_id
        tests:
          - not_null
          - unique
      - name: account_name
        tests:
          - not_null

  - name: practitioners
    description: |
      List of care practitioners on the care platform

    columns:
      - name: user_id
        tests:
            - not_null
            - unique
      - name: main_specialization
        tests:
          - not_null
          - accepted_values:
              values: ['N/A', 'Nurse Clinician', 'Family Physician',
              'Care Coordinator', 'Physiotherapist',
              'Nurse Practitioner', 'Psychologist', 'Nutritionist',
              'Psychotherapist', 'Work & Life Coach']

  - name: telephone_calls_detailed
    description: a detailed table of telephone calls with additional dimensions
      for filtering

    columns:
      - name: call_id
        tests:
          - not_null
          - unique
      - name: started_at_est
        tests:
          - not_null
      - name: practitioner_id
        tests:
          - not_null
      - name: main_specialization
        tests:
          - not_null

  - name: user_contract
    columns:
      - name: contract_id
        tests:
          - not_null
      - name: user_id
        tests:
          - not_null
      - name: organization_id
        tests:
          - not_null
      - name: participant_id
        tests:
          - not_null
      - name: during
        tests:
          - not_null
      - name: organization_is_paid
        tests:
          - not_null
      - name: is_employee
        tests:
          - not_null
      - name: is_child
        tests:
          - not_null
      - name: family_member_type
        tests:
          - not_null
          - accepted_values:
              values: ['Employee', 'Child', 'Dependent']
      - name: language
        tests:
          - not_null
          - accepted_values:
              values: ['FR', 'EN']
      - name: gender
        tests:
          # TODO remove N/A once there are no active users without gender set
          - accepted_values:
              values: ['M', 'F', 'N/A']
      - name: residence_province
        tests:
          - not_null
          - accepted_values:
              values: ['Prince Edward Island', 'Alberta', 'Ontario',
              'Saskatchewan', 'British Columbia', 'Manitoba', 'Quebec',
              'New Brunswick', 'Nova Scotia', 'Yukon',
              'Newfoundland and Labrador']
      - name: residence_province_code
        tests:
          - not_null
      - name: residence_province
        tests:
          - not_null
      - name: account_id
        tests:
          - not_null
      - name: account_name
        tests:
          - not_null
      - name: features
        tests:
          - not_null
      - name: has_mental_health
        tests:
          - not_null
          - accepted_values:
              values: [true, false]
      - name: has_24_7
        tests:
          - not_null
          - accepted_values:
              values: [true, false]

    tests:
      - unique:
          column_name: "concat(user_id, contract_id)"

  - name: post_submitted
    description: is_alive style event for reporting on device and user attributes
      NB it has a lot of overlap with active users and chats in terms of usage
    columns:
      - name: event_id
        tests:
          - not_null
      - name: episode_id
        tests:
          - not_null

    tests:
      - unique:
          column_name: "concat(event_id, contract_id)"
