
version: 2

models:
  - name: organizations
    columns:
      - name: organization_id
        tests:
          - not_null
          - unique

      - name: organization_name
        tests:
          - not_null

      - name: account_id
        tests:
          - not_null

      - name: account_name
        tests:
          - not_null

      - name: account_industry
        tests:
          - not_null

  - name: meta_accounts_monthly
    columns:
      - name: account_id
        tests:
          - not_null

      - name: account_name
        tests:
          - not_null

      - name: active_contracts
        tests:
          - not_null

      - name: price_monthly
        tests:
          - not_null

      - name: active_contracts_last_month
        tests:
          - not_null

      - name: price_monthly_last_month
        tests:
          - not_null

    tests:
      - unique:
          column_name: "concat(date_month, account_id)"

  - name: video_started
    columns:
      - name: timestamp
        tests:
          - not_null

      - name: patient_id
        tests:
          - not_null

      - name: main_specialization
        tests:
          - not_null

  - name: videos_daily
    columns:
      - name: date_day
        tests:
          - not_null

      - name: patient_id
        tests:
          - not_null

      - name: includes_video_gp
        tests:
          - not_null

      - name: includes_video_np
        tests:
          - not_null

      - name: includes_video_nc
        tests:
          - not_null

      - name: includes_video_cc
        tests:
          - not_null

    tests:
      - unique:
          column_name: "concat(date_day, patient_id)"

  - name: videos_by_ep_daily
    columns:
      - name: date_day
        tests:
          - not_null

      - name: episode_id
        tests:
          - not_null

      - name: patient_id
        tests:
          - not_null

      - name: includes_video_gp
        tests:
          - not_null

      - name: includes_video_np
        tests:
          - not_null

      - name: includes_video_nc
        tests:
          - not_null

      - name: includes_video_cc
        tests:
          - not_null

    tests:
      - unique:
          column_name: "concat(date_day_est, episode_id, patient_id)"

  - name: active_users
    columns:
      - name: dau_id
        tests:
          - not_null
          - unique

      - name: patient_id
        tests:
          - not_null

      - name: date_day
        tests:
          - not_null

  - name: episodes
    description: A table containing episodes with details for analysis

    columns:
        - name: episode_id
          description: This is a unique identifier for the episode
          tests:
              - unique
              - not_null
    tests:
      - dbt_utils.recency:
          field: created_at
          datepart: day
          interval: 1

  - name: cp_activity
    description: A table containing activities completed by practitioners in
      the Care Platform as estimated by `page` and `video` events

    columns:
        - name: time_spent
          tests:
              - not_null
        - name: user_id
          tests:
              - not_null
    tests:
      - dbt_utils.recency:
          field: activity_start
          datepart: day
          interval: 1


  - name: cp_activity_detailed
    description: CP Activity but with additional analytical details from
      episodes

    columns:
        - name: time_spent
          tests:
              - not_null
    tests:
      - dbt_utils.recency:
          field: activity_start
          datepart: day
          interval: 1

  - name: chats_all_time
    description: A table containing daily episode activity with details about
      what activity was done in that episode on that day

    columns:
        - name: episode_id
          tests:
              - not_null
    tests:
      - dbt_utils.recency:
          field: created_at_day
          datepart: day
          interval: 1

  - name: nps_patient_survey
    columns:
      - name: user_id
        tests:
          - not_null

      - name: score
        tests:
          - not_null

      - name: category
        tests:
          - not_null
          - accepted_values:
              values: ['promoter', 'passive', 'detractor']

      - name: organization_id
        tests:
          - not_null
