
version: 2

models:
  - name: assigned_time
    columns:
      - name: episode_id
        tests:
          - not_null
      - name: assigned_at
        tests:
          - not_null

    tests:
      - unique:
          column_name: "concat(assigned_at, episode_id)"

  - name: assigned_time_detailed
    columns:
      - name: episode_id
        tests:
          - not_null
      - name: assigned_at
        tests:
          - not_null
      - name: main_specialization
        tests:
          - not_null
      - name: assignment_type
        tests:
          - not_null

    tests:
      - unique:
          column_name: "concat(assigned_at, episode_id)"

  - name: chats
    columns:
      - name: episode_id
        tests:
          - not_null
      - name: date_day_est
        tests:
          - not_null
      - name: initiator
        tests:
          - not_null
      - name: has_open_reminder
        tests:
          - not_null
      - name: set_resolved_pending
        tests:
          - not_null
      - name: chat_type
        tests:
          - not_null

    tests:
      - unique:
          column_name: "concat(episode_id, date_day_est)"

  - name: organizations
    columns:
      - name: organization_id
        tests:
          - not_null
          - unique

      - name: organization_name
        tests:
          - not_null

      - name: account_id
        tests:
          - not_null

      - name: account_name
        tests:
          - not_null

      - name: account_industry
        tests:
          - not_null

  - name: organizations_monthly
    columns:
      - name: date_month
        tests:
          - not_null
      - name: organization_name
        tests:
          - not_null

    tests:
      - unique:
          column_name: "concat(date_month, organization_id)"


  - name: meta_accounts_monthly
    columns:
      - name: account_id
        tests:
          - not_null

      - name: account_name
        tests:
          - not_null

      - name: active_contracts
        tests:
          - not_null

      - name: price_monthly
        tests:
          - not_null

      - name: active_contracts_last_month
        tests:
          - not_null

      - name: price_monthly_last_month
        tests:
          - not_null

    tests:
      - unique:
          column_name: "concat(date_month, account_id)"

  - name: video_started
    description: a video start model to join the various events used for
      tracking this over time; this table is also tested in a data test on
      uniqueness of patients to test for an edge case found in certain records
    columns:
      - name: timestamp
        tests:
          - not_null

      - name: patient_id
        tests:
          - not_null

      - name: main_specialization
        tests:
          - not_null

  - name: videos_daily
    columns:
      - name: date_day
        tests:
          - not_null

      - name: patient_id
        tests:
          - not_null

      - name: includes_video_gp
        tests:
          - not_null

      - name: includes_video_np
        tests:
          - not_null

      - name: includes_video_nc
        tests:
          - not_null

      - name: includes_video_cc
        tests:
          - not_null

    tests:
      - unique:
          column_name: "concat(date_day, patient_id)"

  - name: videos_by_ep_daily
    columns:
      - name: date_day_est
        tests:
          - not_null

      - name: episode_id
        tests:
          - not_null

      - name: patient_id
        tests:
          - not_null

      - name: includes_video_gp
        tests:
          - not_null

      - name: includes_video_np
        tests:
          - not_null

      - name: includes_video_nc
        tests:
          - not_null

      - name: includes_video_cc
        tests:
          - not_null

    tests:
      - unique:
          column_name: "concat(date_day_est, episode_id, patient_id)"

  - name: videos_detailed
    description: a table with one record per video with details about video
      start time, specialization of practitioner, and duration; there is a
      data test to validate than no more than 4% of videos have an undefined
      video length in a given week (`assert_videos_length`)
    columns:
      - name: date_day_est
        tests:
          - not_null

      - name: episode_id
        tests:
          - not_null

      - name: main_specialization
        tests:
          - not_null

  - name: active_users
    columns:
      - name: dau_id
        tests:
          - not_null

      - name: patient_id
        tests:
          - not_null

      - name: date_day
        tests:
          - not_null

      - name: family_member_type
        tests:
          - not_null
          - accepted_values:
              values: ['Employee', 'Dependent', 'Child']

  - name: active_users_weekly
    columns:
      - name: date_week
        tests:
          - not_null
          - unique

      - name: waus
        tests:
          - not_null

      - name: daus
        tests:
          - not_null

      - name: daus_chat
        tests:
          - not_null

      - name: daus_video_gp_np
        tests:
          - not_null

      - name: waus_paid
        tests:
          - not_null

      - name: daus_paid
        tests:
          - not_null

      - name: daus_chat_paid
        tests:
          - not_null

  - name: active_users_monthly
    columns:
      - name: date_month
        tests:
          - not_null
          - unique

      - name: maus
        tests:
          - not_null

      - name: daus
        tests:
          - not_null
          
      - name: daus_chat
        tests:
          - not_null
          
      - name: daus_video_gp_np
        tests:
          - not_null
          
      - name: maus_paid
        tests:
          - not_null
          
      - name: daus_paid
        tests:
          - not_null
          
      - name: daus_chat_paid
        tests:
          - not_null
          
      - name: daus_video_gp_np_paid
        tests:
          - not_null

  - name: episodes
    description: A table containing episodes with details for analysis

    columns:
        - name: episode_id
          description: This is a unique identifier for the episode
          tests:
              - unique
              - not_null
    tests:
      - dbt_utils.recency:
          field: created_at
          datepart: day
          interval: 1

  - name: chats_all_time
    description: A table containing daily episode activity with details about
      what activity was done in that episode on that day

    columns:
        - name: episode_id
          tests:
              - not_null
    tests:
      - dbt_utils.recency:
          field: last_message_created_at
          datepart: hour
          interval: 24
      - unique:
          column_name: "concat(created_at_day, episode_id)"


  - name: nps_patient_survey
    columns:
      - name: user_id
        tests:
          - not_null

      - name: score
        tests:
          - not_null

      - name: category
        tests:
          - not_null
          - accepted_values:
              values: ['promoter', 'passive', 'detractor']

      - name: organization_id
        tests:
          - not_null

  - name: accounts
    columns:
      - name: account_id
        tests:
          - not_null
          - unique

      - name: account_name
        tests:
          - not_null

  - name: practitioners
    description: |
      List of care practitioners on the care platform

    columns:
      - name: user_id
        tests:
            - not_null
            - unique

      - name: main_specialization
        tests:
          - not_null
          - accepted_values:
              values: ['N/A', 'Nurse Clinician', 'Family Physician',
              'Care Coordinator', 'Physiotherapist',
              'Nurse Practitioner', 'Psychologist', 'Nutritionist',
              'Psychotherapist', 'Work & Life Coach']

  - name: user_contract
    columns:
      - name: contract_id
        tests:
          - not_null

      - name: user_id
        tests:
          - not_null

      - name: organization_id
        tests:
          - not_null

      - name: participant_id
        tests:
          - not_null

      - name: during
        tests:
          - not_null

      - name: organization_is_paid
        tests:
          - not_null

      - name: is_employee
        tests:
          - not_null

      - name: is_child
        tests:
          - not_null

      - name: family_member_type
        tests:
          - not_null
          - accepted_values:
              values: ['Employee', 'Child', 'Dependent']

      - name: language
        tests:
          - not_null
          - accepted_values:
              values: ['FR', 'EN']

      - name: residence_province
        tests:
          - not_null
          - accepted_values:
              values: ['Prince Edward Island', 'Alberta', 'Ontario',
              'Saskatchewan', 'British Columbia', 'Manitoba', 'Quebec',
              'New Brunswick', 'Nova Scotia', 'Yukon',
              'Newfoundland and Labrador']

      - name: account_id
        tests:
          - not_null

      - name: account_name
        tests:
          - not_null

    tests:
      - unique:
          column_name: "concat(user_id, contract_id)"
