version: 2

models:
  - name: jira_issues
    columns:
        - name: issue_id
          tests:
              - unique
              - not_null
        - name: status
          tests:
              - not_null
        - name: created_at
          tests:
              - not_null
        - name: issue_type
          tests:
              - not_null
              - relationships:
                  to: ref('valid_jira_issue_types')
                  field: issue_type
        - name: project_name
          tests:
              - not_null
    # TODO find solution for recency excl. weekends
    tests:
      - dbt_utils.recency:
          field: created_at
          datepart: day
          interval: 3
      - dbt_utils.recency:
          field: updated_at
          datepart: day
          interval: 3

  - name: jira_incident_count
    description: |
      This model abstracts daily incident count from the incident_count field
      on Jira Issues; it is used in QA reporting.
    columns:
        - name: issue_id
          tests:
              - not_null
        - name: date_day
          tests:
              - not_null
    tests:
      - unique:
          column_name: "concat(issue_id, date_day)"
