
version: 2

models:
  - name: tableau_medops_scorecard_stats_by_shift
    description: An analytical table for measuring medops performance by
      shift; includes facts about response times and output and is aggregated
      at the shift-level to ensure there is only one position per record.
    columns:
      - name: date_day
        tests:
          - not_null
      - name: user_id
        tests:
          - not_null
      - name: shift_id
        tests:
          - not_null
          - unique
