version: 2

models:
  - name: metabase_episodes
    description: A table containing episodes with details for analysis in
      Metabase's webapp

    columns:
        - name: episode_id
          description: This is a unique identifier for the episode
          tests:
              - unique
              - not_null
    tests:
      - dbt_utils.recency:
          field: created_at
          datepart: day
          interval: 1

  - name: metabase_patients
    columns:
        - name: patient_id
          tests:
              - unique
              - not_null

  - name: metabase_bonjour_sante
    columns:
        - name: episode_id
          tests:
              - not_null
        - name: triggered_at
          tests:
              - not_null
    tests:
      - unique:
          column_name: "concat(triggered_at, episode_id)"
