
version: 2

models:
  - name: xero_cac

    columns:
      - name: date_month
        tests:
          - not_null
          - unique

      - name: cost_eae_qc
        tests:
          - not_null

      - name: cost_eae_roc
        tests:
          - not_null

      - name: cost_ae_qc
        tests:
          - not_null

      - name: cost_ae_roc
        tests:
          - not_null

      - name: cost_total
        tests:
          - not_null

  - name: xero_profit_and_loss
    description: 'Monthly P&L report by expense account'

    columns:
      - name: date_month
        tests:
          - not_null

      - name: account_group
        tests:
          - not_null
          - accepted_values:
              values: ['Sales Expenses', 'Customer Success',
              'General Administration', 'Health Team',
              'Marketing Expenses', 'Technology']

      - name: account_name
        tests:
          - not_null

      - name: amount_excl_tax
        tests:
          - not_null

    tests:
      - unique:
          column_name: "concat(date_month, account_name)"
