
version: 2

models:
  - name: xero_profit_and_loss
    description: 'Monthly P&L report by expense account'

    columns:
      - name: date_month
        tests:
          - not_null

      - name: account_group
        tests:
          - not_null
          - accepted_values:
              values: ['Sales Expenses', 'Customer Success',
              'General Administration', 'Health Team',
              'Marketing Expenses', 'Technology', 'N/A']

      - name: account_name
        tests:
          - not_null

      - name: amount
        tests:
          - not_null

    tests:
      - unique:
          column_name: "concat(date_month, account_name)"

  - name: xero_cac
    columns:
      - name: date_month
        tests:
          - not_null
          - unique

      - name: cost_eae
        tests:
          - not_null

      - name: cost_ae
        tests:
          - not_null
