
version: 2

models:
  - name: patientapp_video_session_connect_success
    columns:
      - name: user_id
        tests:
          - not_null

  - name: patientapp_submit_post_success
    columns:
      - name: user_id
        tests:
          - not_null

      - name: platform_name
        tests:
          - not_null
          - accepted_values:
              values: ['iOS', 'Android', 'Desktop']

    tests:
      - dbt_utils.recency:
          field: timestamp
          datepart: hour
          interval: 15

  - name: patientapp_login_fetch_complete
    columns:
      - name: user_id
        tests:
          - not_null
