
version: 2

models:
  - name: countdown_tracks
    columns:
      - name: timestamp
        tests:
          - not_null
    tests:
      - dbt_utils.recency:
          field: timestamp
          datepart: hour
          interval: 15

  - name: countdown_question_replied
    columns:
      - name: question_tid
        tests:
          - not_null
          - unique

  - name: countdown_qnaire_completed
    columns:
      - name: qnaire_tid
        tests:
          - not_null
          - unique

  - name: countdown_chief_complaint_parsed
    columns:
      - name: episode_id
        tests:
          - not_null
      - name: cc_name
        tests:
          - not_null
      - name: cc_confidence
        tests:
          - not_null
      - name: confidence_threshold
        tests:
          - not_null

  - name: countdown_qnaire_resumed
    columns:
      - name: qnaire_tid
        tests:
          - not_null
