version: 2

models:
  - name: user_activated
    columns:
      - name: user_id
        tests:
          - not_null
          - unique

      - name: activated_at
        tests:
          - not_null

  - name: users_paid_employees_monthly
    columns:
        - name: organization_id
          tests:
              - not_null
        - name: date_month
          tests:
              - not_null
    tests:
      - unique:
          column_name: "concat(date_month, organization_id)"
