version: 2

models:
  - name: medops_mau_by_org
    columns:
        - name: organization_name
          tests:
              - not_null

  - name: medops_priced_videos
    columns:
        - name: episode_id
          tests:
              - not_null
        - name: date
          tests:
              - not_null
    tests:
        - unique:
          column_name: "concat(date, episode_id)"

  - name: medops_priced_episodes
    columns:
        - name: episode_id
          tests:
              - not_null
        - name: date
          tests:
              - not_null
    tests:
        - unique:
          column_name: "concat(date, episode_id)"

  - name: medops_daily_time_spent
    columns:
        - name: episode_id
          tests:
              - not_null
        - name: date
          tests:
              - not_null
    tests:
        - unique:
          column_name: "concat(date, episode_id)"

  - name: medops_est_costs_by_org_monthly
    columns:
        - name: organization_name
          tests:
              - not_null
        - name: month
          tests:
              - not_null
    tests:
        - unique:
          column_name: "concat(organization_name, month)"

  - name: medops_cost_per_video_daily.sql
    columns:
        - name: date
          tests:
              - not_null
              - unique

        - name: count_videos
          tests:
              - not_null

        - name: cost_per_video
          tests:
              - not_null

  - name: medops_time_to_next_apt
    columns:
        - name: episode_id
          tests:
              - not_null
        - name: triggered_at
          tests:
              - not_null
    tests:
        - unique:
          column_name: "concat(episode_id, triggered_at)"
