
version: 2

models:
  - name: finance_gm_breakdown
    description: This seed is two records per month respectively for GM1's and
      Sales' affect on our burn. The seed is appended to from this google sheet,
      refer to line 217 and below -
      https://docs.google.com/spreadsheets/d/1NYPJaaot8ckw6HL_88IP63Rmx8jiJ4NM14RjyZyISLc/edit#gid=211783943
    columns:
      - name: date_month
        tests:
          - not_null
      - name: gm_source
        tests:
          - not_null
      - name: value
        tests:
          - not_null

    tests:
      - unique:
          column_name: "concat(date_month, gm_source)"

  - name: finance_runway
    description: This seed is one record per month of actual runway and
      forecasted runway for future months. This seed is updated fully every
      month and is from this google sheet -
      https://docs.google.com/spreadsheets/d/1YIvESSs8XaaYd7Q8tMl8I0YTtVMy68a7HNft__CRu9g/edit?ts=5c364158#gid=0
    columns:
      - name: date_month
        tests:
          - not_null
          - unique
      - name: forecast
        tests:
          - not_null

  - name: finance_opex
    description: This seed is one record per department per month with a value
      for the delta between actual and budgeted spend. The seed is appended to
      from this google sheet, refer to line 217 and below -
      https://docs.google.com/spreadsheets/d/1NYPJaaot8ckw6HL_88IP63Rmx8jiJ4NM14RjyZyISLc/edit#gid=211783943
    columns:
      - name: date_month
        tests:
          - not_null
      - name: department
        tests:
          - not_null
      - name: delta
        tests:
          - not_null

  - name: finance_revenue_and_costs_monthly
    description: This seed is one record per month with columns for revenue
      and costs by main specialization. These revenues and cost numbers are
      used in our GM calculations. The seed is downloaded from this google
      sheet -
      https://docs.google.com/spreadsheets/d/1OY75vKFMPCnMiMVwOwmNd1igR9SO81q4IYHxLjZp8hc/edit#gid=545957709
    columns:
      - name: date_month
        tests:
          - not_null
          - unique
      - name: telehealth_revenue
        tests:
          - not_null
      - name: mrr
        tests:
          - not_null
      - name: fl_gp_cost
        tests:
            - not_null
      - name: fl_np_cost
        tests:
            - not_null
      - name: fl_nc_cost
        tests:
            - not_null
      - name: fl_cc_cost
        tests:
            - not_null
      - name: bonjour_sante_cost
        tests:
            - not_null
      - name: license_cost
        tests:
            - not_null
      - name: saas_cost
        tests:
            - not_null
    tests:
      - dbt_utils.recency:
          datepart: day
          field: date_month
          interval: 45

  - name: finance_revenue_adjustment
    description: This seed is an extract from Xero; the data is one record
      per journal entry where every journal entry is associated with an
      account and a month. The entry descriptions are then joined to
      organization names to produce revenue per account per month. The seed
      is downloaded from this google sheet -
      https://docs.google.com/spreadsheets/d/17xtKWgnFBFfWaZQZVhoD3l_KOp5pfmgi250Zgswrch8/edit#gid=405697240
    tests:
      - unique:
          column_name: "concat(account, month)"

  - name: finance_adjusted_revenue_monthly
    description: |
      Amount recognized each month by account (salesforce accounts).

      This file is created by the finance team as it does not match the amount
      paid each month. An example of differences is if a client prepays for
      6 monhts, the amount will be recognized monthly over the full period.
      Source (updated monthly by the finance team):
      https://docs.google.com/spreadsheets/d/1wkvGi9P_08nZP_dbyBm8IN50ekc-xjtzwZoMSN05ZPI/edit?ts=5c4613ec#gid=1284329052
    columns:
      - name: date_month
        tests:
          - not_null
      - name: account_id
        tests:
          - not_null
          - relationships:
              to: ref('salesforce_accounts')
              field: account_id
      - name: account_name
        tests:
          - not_null

  - name: finance_pilot_expansions
    description: |
      Companies and month excluded from the churn calculation as they represent
      pilot expansions instead of organic or rep-lead expansions
    columns:
      - name: account_id
        tests:
          - not_null
          - relationships:
              to: ref('salesforce_accounts')
              field: account_id
      - name: date_month
        tests:
          - not_null

  - name: finance_rampup_cost
    description: |
      Costs associated to AEs and EAEs in their first 6 months

      Excluded from LTV:CAC excluding ramp calculation

      source: https://docs.google.com/spreadsheets/d/1vbG8wVFAjIiqeWeiJJhpvIDf2YfpCnQljYE7PRuT0tw/edit#gid=274028474
    columns:
      - name: date_month
        tests:
          - not_null
      - name: cost_ae_ramp
        tests:
          - not_null
      - name: cost_eae_ramp
        tests:
          - not_null
