
version: 2

models:
  - name: finance_gm_breakdown
    description: This seed is two records per month respectively for GM1's and
      Sales' affect on our burn. The seed is appended to from this google sheet,
      refer to line 217 and below -
      https://docs.google.com/spreadsheets/d/1NYPJaaot8ckw6HL_88IP63Rmx8jiJ4NM14RjyZyISLc/edit#gid=211783943
    columns:
      - name: date_month
        tests:
          - not_null

      - name: gm_source
        tests:
          - not_null

      - name: value
        tests:
          - not_null

    tests:
      - unique:
          column_name: "concat(date_month, gm_source)"

  - name: finance_runway
    description: This seed is one record per month of actual runway and
      forecasted runway for future months. This seed is updated fully every
      month and is from this google sheet -
      https://docs.google.com/spreadsheets/d/1YIvESSs8XaaYd7Q8tMl8I0YTtVMy68a7HNft__CRu9g/edit?ts=5c364158#gid=0
    columns:
      - name: date_month
        tests:
          - not_null
          - unique

      - name: forecast
        tests:
          - not_null

  - name: finance_opex
    description: This seed is one record per department per month with a value
      for the delta between actual and budgeted spend. The seed is appended to
      from this google sheet, refer to line 217 and below -
      https://docs.google.com/spreadsheets/d/1NYPJaaot8ckw6HL_88IP63Rmx8jiJ4NM14RjyZyISLc/edit#gid=211783943
    columns:
      - name: date_month
        tests:
          - not_null

      - name: department
        tests:
          - not_null

      - name: delta
        tests:
          - not_null

  - name: finance_revenue_and_costs_monthly
    description: This seed is one record per month with columns for revenue
      and costs by main specialization. These revenues and cost numbers are
      used in our GM calculations. The seed is downloaded from this google
      sheet -
      https://docs.google.com/spreadsheets/d/1OY75vKFMPCnMiMVwOwmNd1igR9SO81q4IYHxLjZp8hc/edit#gid=545957709
    columns:
      - name: date_month
        tests:
          - not_null
          - unique

      - name: telehealth_revenue
        tests:
          - not_null

      - name: mrr
        tests:
          - not_null

      - name: fl_gp_cost
        tests:
            - not_null

      - name: fl_np_cost
        tests:
            - not_null

      - name: fl_nc_cost
        tests:
            - not_null

      - name: fl_cc_cost
        tests:
            - not_null

      - name: other_cost
        tests:
            - not_null

  - name: finance_revenue_adjustment
    description: This seed is an extract from Xero; the data is one record
      per journal entry where every journal entry is associated with an
      account and a month. The entry descriptions are then joined to
      organization names to produce revenue per account per month. The seed
      is downloaded from this google sheet -
      https://docs.google.com/spreadsheets/d/17xtKWgnFBFfWaZQZVhoD3l_KOp5pfmgi250Zgswrch8/edit#gid=405697240
    tests:
      - unique:
          column_name: "concat(account, month)"
