
version: 2

models:
  - name: xero_expenses
    description: 'Xero expenses going in the P&L report'

    columns:
      - name: line_amount_excl_tax
        description: Amount of the expense exclusive of taxes

  - name: eae_compensation_percentage_monthly
    description: |
      Monthly percentage of account executive total compensation
      associated to the enterprise segment

    columns:
      - name: date_month
        tests:
          - not_null
          - unique

      - name: eae_compensation_percentage
        tests:
          - not_null
