version: 2

models:
  - name: jira_issues
    columns:
        - name: issue_id
          tests:
              - unique
              - not_null
        - name: status
          tests:
              - not_null
        - name: created_at
          tests:
              - not_null
        - name: issue_type
          tests:
              - not_null
              - relationships:
                  to: ref('valid_jira_issue_types')
                  field: issue_type
        - name: project_name
          tests:
              - not_null
    # TODO find solution for recency excl. weekends
    tests:
      - dbt_utils.recency:
          field: created_at
          datepart: day
          interval: 3
      - dbt_utils.recency:
          field: updated_at
          datepart: day
          interval: 3
