version: 2

models:
  - name: mental_health_pilot_patients
    description: A table containing mental health pilot patients with details for analysis

    columns:
        - name: episode_id
          description: This is a unique identifier for the episode
          tests:
              - unique
              - not_null
