version: 2

models:
  - name: funnelio_choozle
    columns:
        - name: date_day
          tests:
              - not_null
        - name: platform
          tests:
              - not_null
        - name: channel
          tests:
              - not_null
        - name: clicks
          tests:
              - not_null
        - name: impressions
          tests:
              - not_null
        - name: cost
          tests:
              - not_null
    tests:
      - unique:
          column_name: "concat(date_day, channel)"

  - name: funnelio_facebook
    columns:
        - name: date_day
          tests:
              - not_null
        - name: platform
          tests:
              - not_null
        - name: channel
          tests:
              - not_null
        - name: clicks
          tests:
              - not_null
        - name: impressions
          tests:
              - not_null
        - name: cost
          tests:
              - not_null
    tests:
      - unique:
          column_name: "concat(date_day, channel)"

  - name: funnelio_google
    columns:
        - name: date_day
          tests:
              - not_null
        - name: platform
          tests:
              - not_null
        - name: channel
          tests:
              - not_null
        - name: clicks
          tests:
              - not_null
        - name: impressions
          tests:
              - not_null
        - name: cost
          tests:
              - not_null
    tests:
      - unique:
          column_name: "concat(date_day, channel)"

  - name: funnelio_linkedin
    columns:
        - name: date_day
          tests:
              - not_null
        - name: platform
          tests:
              - not_null
        - name: channel
          tests:
              - not_null
        - name: clicks
          tests:
              - not_null
        - name: impressions
          tests:
              - not_null
        - name: cost
          tests:
              - not_null
    tests:
      - unique:
          column_name: "concat(date_day, channel)"

  - name: funnelio_linkedin_organic
    columns:
        - name: date_day
          tests:
              - not_null
        - name: platform
          tests:
              - not_null
        - name: channel
          tests:
              - not_null
        - name: clicks
          tests:
              - not_null
        - name: impressions
          tests:
              - not_null
        - name: cost
          tests:
              - not_null
    tests:
      - unique:
          column_name: "concat(date_day, channel)"

  - name: funnelio_other
    columns:
        - name: date_day
          tests:
              - not_null
        - name: platform
          tests:
              - not_null
        - name: channel
          tests:
              - not_null
        - name: clicks
          tests:
              - not_null
        - name: impressions
          tests:
              - not_null
        - name: cost
          tests:
              - not_null
    tests:
      - unique:
          column_name: "concat(date_day, channel)"

  - name: funnelio_twitter
    columns:
        - name: date_day
          tests:
              - not_null
        - name: platform
          tests:
              - not_null
        - name: channel
          tests:
              - not_null
        - name: clicks
          tests:
              - not_null
        - name: impressions
          tests:
              - not_null
        - name: cost
          tests:
              - not_null
    tests:
      - unique:
          column_name: "concat(date_day, channel)"
