version: 2

models:
  - name: chats_reminders_daily
    columns:
      - name: episode_id
        tests:
          - not_null
      - name: date_day_est
        tests:
          - not_null
    tests:
      - unique:
          column_name: "concat(date_day_est, episode_id)"

  - name: chats_outcomes_daily
    columns:
      - name: episode_id
        tests:
          - not_null
      - name: date_day_est
        tests:
          - not_null
    tests:
      - unique:
          column_name: "concat(date_day_est, episode_id)"

  - name: chats_state_changes_daily
    columns:
      - name: episode_id
        tests:
          - not_null
      - name: date_day_est
        tests:
          - not_null
    tests:
      - unique:
          column_name: "concat(date_day_est, episode_id)"

  - name: chats_messaging_daily
    columns:
      - name: episode_id
        tests:
          - not_null
      - name: date_day_est
        tests:
          - not_null
    tests:
      - unique:
          column_name: "concat(date_day_est, episode_id)"

  - name: chats_out_of_hours_slas
    description: |
      Service Level Aggreement defined with customers for episodes started
      outside of opening hours

      Terms can be found here: https://www.notion.so/godialogue/SLA-3f692ef07f764fc3afbd7610721e0f62
    columns:
      - name: episode_id
        tests:
          - not_null
      - name: date_day_est
        tests:
          - not_null
      - name: is_answered_next_day
        description: |
          Is the message answered on the immediately following business day
        tests:
          - not_null
      - name: is_answered_within_3_opened_hours
        description: |
          Is the message answered on the first 3 hours of the immediately
          following business day
        tests:
          - not_null
      - name: is_pm_chat
        tests:
          - not_null
    tests:
      - unique:
          column_name: "concat(date_day_est, episode_id)"
