version: 2

models:
  - name: chats_reminders_daily
    columns:
      - name: episode_id
        tests:
          - not_null
      - name: date_day_est
        tests:
          - not_null
    tests:
      - unique:
          column_name: "concat(date_day_est, episode_id)"

  - name: chats_outcomes_daily
    columns:
      - name: episode_id
        tests:
          - not_null
      - name: date_day_est
        tests:
          - not_null
    tests:
      - unique:
          column_name: "concat(date_day_est, episode_id)"

  - name: chats_state_changes_daily
    columns:
      - name: episode_id
        tests:
          - not_null
      - name: date_day_est
        tests:
          - not_null
    tests:
      - unique:
          column_name: "concat(date_day_est, episode_id)"

  - name: chats_messaging_daily
    columns:
      - name: episode_id
        tests:
          - not_null
      - name: date_day_est
        tests:
          - not_null
    tests:
      - unique:
          column_name: "concat(date_day_est, episode_id)"
