
version: 2

models:

  - name: finance_ltv_to_cac
    columns:
      - name: date_month
        tests:
          - not_null

      - name: cost_total
        tests:
          - not_null

      - name: cost_eae
        tests:
          - not_null

      - name: cost_ae

      - name: mrr_signed
        tests:
          - not_null

      - name: mrr_signed_eae
        tests:
          - not_null

      - name: mrr_signed_ae
        tests:
          - not_null

  - name: finance_revenue_adjusted_monthly
    description: This is a journal entry level model that allows us to test for
      uniqueness on the account description + month basis; this is necessary
      because of the fuzzy join used
    ## Comment out test because the fuzzy join is brittle
    # tests:
      # - unique:
      #     column_name: "concat(account, month)"

  - name: finance_revenue_adjusted_by_account_monthly
    description: One record per account per month of their adjusted revenue as
      it's listed in Xero; this information is extracted from Xero and then
      joined to our DB's organization names.
      NB - ideally in the future we would have organization_ids on invoices so
      this fuzzy joining is not necessary
    tests:
      - unique:
          column_name: "concat(account_name, month)"

  - name: finance_revenue_adjusted_by_account_monthly_v2
    description: |
      Monthly adjusted revenue by account including all sources of revenue

    columns:
      - name: date_month
        tests:
          - not_null

      - name: account_id
        tests:
          - not_null

      - name: amount
        tests:
          - not_null

    tests:
      - unique:
          column_name: "concat(account_id, date_month)"

  - name: finance_churn_monthly
    description: |
      Month over month recognized amount variation by account

    columns:
      - name: date_month
        tests:
          - not_null

      - name: account_id
        tests:
          - not_null

      - name: account_name
        tests:
          - not_null

      - name: amount
        tests:
          - not_null

      - name: amount
        tests:
          - not_null

      - name: amount_variation
        tests:
          - not_null

      - name: amount_variation_type
        tests:
          - not_null
          - accepted_values:
              values: ['Expansion', 'Contraction', 'Stable', 'New', 'Churned']

    tests:
      - unique:
          column_name: "concat(account_id, date_month)"

  - name: finance_psy_pilot_fraction
    description: |
      Fraction of costs attributed to PSY-Pilot episodes; this serves a
      metabase question that finance uses monthly

    columns:
      - name: date_month
        tests:
          - not_null
          - unique

  - name: finance_revenue_by_account_monthly
    description: |
      Monthly recognized telehealth revenue by account

      In 2017 the revenue is estimated based on the organization's PEPM and
      number of scribe contracts. In 2018 the revenue comes from manual
      adjustment from accounting

    columns:
      - name: date_month
        tests:
          - not_null
      - name: account_id
        tests:
          - not_null
      - name: account_name
        tests:
          - not_null
      - name: amount
        tests:
          - not_null
    tests:
      - unique:
          column_name: "concat(account_id, date_month)"
