version: 2

models:
  - name: mental_health_pilot_patients
    description: A table containing mental health pilot patients with details 
      for analysis

    columns:
        - name: episode_id
          tests:
              - unique
              - not_null

  - name: mental_health_qnaire_answers
    description: A table containing responses to the Stress Questionnaire 
      that's used for triaging PSY Pilot patients

    columns:
        - name: stress_qnaire_completed_at
          tests:
              - not_null
        - name: qnaire_tid
          tests:
              - unique
              - not_null

  - name: mental_health_utilization_by_org_weekly
    description: A record per organization per month with details about estimated
      revenue, estimated margin, utilization, etc.
    columns:
        - name: date_week
          tests:
              - not_null
        - name: organization_name
          tests:
              - not_null
        - name: organization_id
          tests:
              - not_null
    tests:
        - unique:
            column_name: "concat(date_week, organization_id)"


  - name: mental_health_eligible_episodes
    description: A list of episodes that are eligible for the PSY Pilot program
      but were for some reason not enrolled (i.e. psy issue type, plan has mental
      health, is started after October 31, and is an employee)

    columns:
        - name: episode_id
          tests:
              - not_null
              - unique

  - name: mental_health_phq9_scores
    description: A record per completed PHQ9 with details about the user and
      episode to then be used in longitudinal analysis on a per user basis.
    columns:
        - name: qnaire_tid
          tests:
              - not_null
              - unique
        - name: score
          tests:
              - not_null
        - name: rank
          tests:
              - not_null

  - name: mental_health_phq9_user_summaries
    description: A record per user with pivoted columns for how PHQ9 scores have
      changed over time
    columns:
        - name: user_id
          tests:
              - not_null
              - unique
        - name: score_first
          tests:
              - not_null
