version: 2

models:
  - name: dxa_cc_classifier_data
    description: pulls data from countdown with cc codes or not, answers to
      question == ask_symptoms
    columns:
        - name: episode_id
          tests:
              - not_null
              - unique
        - name: descript
          tests:
              - not_null
        - name: replied_at
          tests:
              - not_null

  - name: dxa_cc_classifier_data_validated_labels
    description: model for testing cc codes are correct from data_dxa_cc_classifier_data_validated
    columns:
        - name: doctor_label
          tests:
            - not_null

  - name: data_dxa_cc_classifier_data_validated
    description: model for loading data validated by doctors from the csv file
    columns:
        - name: doctor_label
          tests:
            - not_null
        - name: descript
          tests:
            - unique
            - not_null

  - name: dxa_cc_classifier_data_not_validated
    description: dxa_cc_classifier_data that does not yet have a doctor_label
    columns:
        - name: episode_id
          tests:
              - not_null
              - unique
        - name: descript
          tests:
              - not_null
        - name: replied_at
          tests:
              - not_null
