version: 2

models:
  - name: episodes_kpis
    description: active time spent by various functions aggregated within daily,
      7-day, and all-time timeframes at the episode level
    columns:
        - name: episode_id
          tests:
              - unique
              - not_null

  - name: episodes_valid_outcome_issue_type_pairs
    description: A list of issue_type and outcome pairs that are
      included in our definition of Fully Resolved (See OMTM dashboard)
    columns:
        - name: valid_pairs
          tests:
              - unique
              - not_null

  - name: episodes_reason_for_visit
    description: The first reason for visit stated for a given episode
    columns:
        - name: episode_id
          tests:
              - unique
              - not_null
        - name: reason_for_visit
          tests:
              - not_null

  - name: episodes_chief_complaint
    description: The first chief complaint code used to launch DXA in a given
      episode
    columns:
        - name: episode_id
          tests:
              - unique
              - not_null
        - name: cc_code
          tests:
              - not_null
        - name: timestamp
          tests:
              - not_null
        - name: timestamp_est
          tests:
              - not_null

  - name: episodes_chats_summary
    description: Facts about messaging, episode state changes, videos, etc.
      that are all derived from the `chats` model; these facts are aggregated
      on an episode grain
    columns:
        - name: episode_id
          tests:
              - not_null
              - unique
              - relationships:
                  to: ref('messaging_channels')
                  field: episode_id

  - name: episodes_with_contracts
    description: Unique episodes are joined to active user_contracts in this
      model; the result is that some episodes may be double counted because
      certain users may have two valid contracts active (e.g. one dependent
      and one employee).
    columns:
        - name: organization_name
          tests:
              - not_null
        - name: organization_id
          tests:
              - not_null
        - name: account_name
          tests:
              - not_null
        - name: account_id
          tests:
              - not_null
        - name: episode_id
              - not_null
        - name: issue_type
          tests:
              - relationships:
                  to: ref('medops_issue_type_labels')
                  field: issue_type
    tests:
      - unique:
          column_name: "concat(episode_id, contract_id)"

  - name: episodes_appointment_booking
    description: timestamp of when the appointment booking template was first
      sent for a given episode
    columns:
        - name: episode_id
          tests:
              - not_null
              - unique
        - name: appointment_booking_first_started_at
          tests:
              - not_null

  - name: episodes_created_sequence_detailed
    description: answers to the initial episodes creation qnaire sequence
      aggregated at the episode level
    columns:
        - name: episode_id
          tests:
              - not_null
              - unique

  - name: episodes_intake
    description: intake groupings calculated on a per episode basis; this is
      derived from a variety of other episode models
    columns:
        - name: episode_id
          tests:
              - not_null
              - unique
        - name: treatment_category
          tests:
              - not_null

  - name: episodes_issue_types
    description: the most recent issue type and details for a given episode
    columns:
        - name: episode_id
          tests:
              - not_null
              - unique
        - name: issue_type
          tests:
              - not_null

  - name: episodes_nps
    description: the most recent NPS score for a given episode
    columns:
        - name: episode_id
          tests:
              - not_null
              - unique
        - name: score
          tests:
              - not_null

  - name: episodes_outcomes
    description: outcome details aggregated at the episode level
    columns:
        - name: episode_id
          tests:
              - not_null
              - unique
        - name: outcome
          tests:
              - not_null
        - name: outcome_category
          tests:
              - not_null

  - name: episodes_priority_levels
    description: priority level details aggregated at the episode level
    columns:
        - name: episode_id
          tests:
              - not_null
              - unique
        - name: priority_level
          tests:
              - not_null

  - name: episodes_ratings
    description: the most recent 5-star rating for a given episode
    columns:
        - name: episode_id
          tests:
              - not_null
              - unique
        - name: rating
          tests:
              - not_null

  - name: episodes_saas_costs
    description: |
      SAAS cost associated to each episode

      Computed by splitting the monthly SAAS costs over the number of new
      episodes during the month
    columns:
        - name: episode_id
          tests:
              - not_null
              - unique
              - relationships:
                  to: ref('messaging_channels')
                  field: episode_id
        - name: saas_cost
          tests:
              - not_null

  - name: episodes_subject
    description: this models corrects the user id associated with the episode
      by referring to who the subject identified is rather than the user who
      is interacting in the episode (this is important for identifying child
      users)
    columns:
        - name: episode_id
          tests:
              - not_null
              - unique
        - name: episode_subject
          tests:
              - not_null

  - name: episodes_video_consultations
    description: facts about video consultations with various specializations
      excluding Nurse Clinican and Care Coordinator aggregated at the episode
      level
    columns:
        - name: episode_id
          tests:
              - not_null
              - unique
        - name: video_consultation_count
          tests:
              - not_null

  - name: episodes_bonjour_sante_costs
    description: |
      Bonjour Sante cost associated to each episode day

      Computed by splitting the monthly Bonjour Sante costs over the number of
      unique days in which the Bonjour Sante template was sent (i.e. if the
      template is sent twice in one day it counts as 1 but if it's sent on two
      separate days it counts as two)

    columns:
        - name: episode_id
          tests:
              - not_null
              - unique
              # TODO: readd when we determine a solution to DM-366
              # - relationships:
              #     to: ref('messaging_channels')
              #     field: episode_id
        - name: bonjour_sante_cost

  - name: episodes_cc_confirmed
    description: the first cc to be confirmed for a given episode
    columns:
        - name: episode_id
          tests:
              - not_null
              - unique
        - name: cc_code
          tests:
              - not_null
        - name: is_cc_confirmed
          tests:
              - not_null

  - name: episodes_costs
    description: |
      All costs associated to an episodes

      Includes time spent by CC, NC, NP, GP, SAAS costs, and Bonjour Sante costs
    columns:
        - name: episode_id
          tests:
              - not_null
              - unique
              # TODO: readd when we determine a solution to DM-366
              # - relationships:
              #     to: ref('messaging_channels')
              #     field: episode_id

  - name: episodes_dispatch_recommendation
    description: |
      Dispatch outcome sent by the nurse after user completes DXA
    columns:
        - name: episode_id
          tests:
              - not_null
              - unique
              # FIXME: test disabled until we have a solution to exclude test
              # episodes (DM-344)
              # - relationships:
              #     to: ref('messaging_channels')
              #     field: episode_id
        - name: dispatch_recommendation
          tests:
              - not_null
              - relationships:
                  to: ref('dimension_dispatch_recommendation')
                  field: dispatch_recommendation
        - name: dispatch_recommendation_timestamp
          tests:
              - not_null
        - name: dispatch_recommendation_timestamp_est
          tests:
              - not_null

  - name: episodes_outcomes
    description: |
      Episode outcome set by the care team in the care platform
    columns:
        - name: episode_id
          tests:
              - not_null
              - unique
        - name: outcome
          tests:
              - not_null
              - relationships:
                  to: ref('careplatform_dimension_outcome')
                  field: outcome
        - name: outcome_category
          tests:
              - not_null
              - relationships:
                  to: ref('careplatform_dimension_outcome')
                  field: outcome_category
        - name: first_outcome
          tests:
              - not_null
              - relationships:
                  to: ref('careplatform_dimension_outcome')
                  field: outcome
        - name: first_outcome_category
          tests:
              - not_null
              - relationships:
                  to: ref('careplatform_dimension_outcome')
                  field: outcome_category
