version: 2

models:
  - name: episodes_kpis

    columns:
        - name: episode_id
          tests:
              - unique
              - not_null

  - name: episodes_valid_outcome_issue_type_pairs
    description: A list of issue_type and outcome pairs that are
      included in our definition of Fully Resolved (See OMTM dashboard)
    columns:
        - name: valid_pairs
          tests:
              - unique
              - not_null

  - name: episodes_reason_for_visit
    description: The first reason for visit stated for a given episode
    columns:
        - name: episode_id
          tests:
              - unique
              - not_null
        - name: reason_for_visit
          tests:
              - not_null

  - name: episodes_chief_complaint
    description: The first chief complaint code used to launch DXA in a given
      episode
    columns:
        - name: episode_id
          tests:
              - unique
              - not_null
        - name: cc_code
          tests:
              - not_null
        - name: timestamp
          tests:
              - not_null
        - name: timestamp_est
          tests:
              - not_null

  - name: episodes_chats_summary
    description: Facts about messaging, episode state changes, videos, etc.
      that are all derived from the `chats` model; these facts are aggregated
      on an episode grain
    columns:
        - name: episode_id
          tests:
              - not_null
              - unique

  - name: episodes_with_contracts
    description: Unique episodes are joined to active user_contracts in this
      model; the result is that some episodes may be double counted because
      certain users may have two valid contracts active (e.g. one dependent
      and one employee).
    columns:
        - name: organization_name
          tests:
              - not_null
        - name: organization_id
          tests:
              - not_null
        - name: account_name
          tests:
              - not_null
        - name: account_id
          tests:
              - not_null
        - name: episode_id
              - not_null
        - name: issue_type
          tests:
              - relationships:
                  to: ref('medops_issue_type_labels')
                  field: issue_type
    tests:
      - unique:
          column_name: "concat(episode_id, contract_id)"

  - name: episodes_chief_complaint
    description: list of chief complaint by episode id
    columns:
        - name: episode_id
          tests:
              - not_null
              - unique
        - name: cc_code
          tests:
              - not_null
        - name: timestamp
          tests:
              - not_null

  - name: episodes_appointment_booking
    description: timestamp of when the appointment booking template was first
      sent for a given episode
    columns:
        - name: episode_id
          tests:
              - not_null
              - unique
        - name: appointment_booking_first_started_at
          tests:
              - not_null
