version: 2

models:
  - name: episodes_kpis
    columns:
        - name: episode_id
          tests:
              - unique
              - not_null

  - name: episodes_valid_outcome_issue_type_pairs
    description: A list of issue_type and outcome pairs that are
      included in our definition of Fully Resolved (See OMTM dashboard)
    columns:
        - name: valid_pairs
          tests:
              - unique
              - not_null

  - name: episodes_reason_for_visit
    description: The first reason for visit stated for a given episode
    columns:
        - name: episode_id
          tests:
              - unique
              - not_null
        - name: reason_for_visit
          tests:
              - not_null

  - name: episodes_chief_complaint
    description: The first chief complaint code used to launch DXA in a given
      episode
    columns:
        - name: episode_id
          tests:
              - unique
              - not_null
        - name: cc_code
          tests:
              - not_null
        - name: timestamp
          tests:
              - not_null
        - name: timestamp_est
          tests:
              - not_null

  - name: episodes_chats_summary
    description: Facts about messaging, episode state changes, videos, etc.
      that are all derived from the `chats` model; these facts are aggregated
      on an episode grain
    columns:
        - name: episode_id
          tests:
              - not_null
              - unique
              - relationships:
                  to: ref('messaging_channels')
                  field: episode_id

  - name: episodes_with_contracts
    description: Unique episodes are joined to active user_contracts in this
      model; the result is that some episodes may be double counted because
      certain users may have two valid contracts active (e.g. one dependent
      and one employee).
    columns:
        - name: organization_name
          tests:
              - not_null
        - name: organization_id
          tests:
              - not_null
        - name: account_name
          tests:
              - not_null
        - name: account_id
          tests:
              - not_null
        - name: episode_id
              - not_null
        - name: issue_type
          tests:
              - relationships:
                  to: ref('medops_issue_type_labels')
                  field: issue_type
    tests:
      - unique:
          column_name: "concat(episode_id, contract_id)"

  - name: episodes_appointment_booking
    description: timestamp of when the appointment booking template was first
      sent for a given episode
    columns:
        - name: episode_id
          tests:
              - not_null
              - unique
        - name: appointment_booking_first_started_at
          tests:
              - not_null

  - name: episodes_saas_costs
    description: |
      SAAS cost associated to each episode

      Computed by splitting the monthly SAAS costs over the number of new
      episodes during the month
    columns:
        - name: episode_id
          tests:
              - not_null
              - unique
              - relationships:
                  to: ref('messaging_channels')
                  field: episode_id
        - name: saas_cost
          tests:
              - not_null

  - name: episodes_costs
    description: |
      All costs associated to an episodes

      Includes time spent by CC, NC, NP, GP and SAAS costs
    columns:
        - name: episode_id
          tests:
              - not_null
              - unique
              - relationships:
                  to: ref('messaging_channels')
                  field: episode_id

  - name: episodes_dispatch_recommendation
    description: |
      Dispatch outcome sent by the nurse after user completes DXA
    columns:
        - name: episode_id
          tests:
              - not_null
              - unique
              # FIXME: test disabled until we have a solution to exclude test
              # episodes (DM-344)
              # - relationships:
              #     to: ref('messaging_channels')
              #     field: episode_id
        - name: dispatch_recommendation
          tests:
              - not_null
              - accepted_values:
                  values: ['Outcome ER', 'Outcome NP or MD', 'Outcome WIC',
                    'Outcome WIC Ubisoft clinic', 'Outcome Counselling',
                    'Outcome Navigation', 'Outcome Rx renewal - Out of scope',
                    'Outcome Rx renewal - Blood pressure',
                    'Outcome Rx renewal - Mental Health',
                    'Outcome WIC PHYSIO',
                    'Outcome Nurse Counselling'
                  ]
        - name: dispatch_recommendation_timestamp
          tests:
              - not_null
        - name: dispatch_recommendation_timestamp_est
          tests:
              - not_null
