version: 2

models:
  - name: episodes_kpis

    columns:
        - name: episode_id
          tests:
              - unique
              - not_null

  - name: episodes_valid_outcome_issue_type_pairs
    description: A list of issue_type and outcome pairs that are
      included in our definition of Fully Resolved (See OMTM dashboard)
    columns:
        - name: valid_pairs
          tests:
              - unique
              - not_null

  - name: episodes_reason_for_visit
    description: The first reson for visit stated for a given episode
    columns:
        - name: episode_id
          tests:
              - unique
              - not_null
        - name: reason_for_visit
          tests:
              - not_null

  - name: episodes_reason_for_visit
    description: The first chief complaint code used to launch DXA in a given
      episode
    columns:
        - name: episode_id
          tests:
              - unique
              - not_null
        - name: reason_for_visit
          tests:
              - not_null

  - name: episodes_with_contracts
    description: Unique episodes are joined to active user_contracts in this
      model; the result is that some episodes may be double counted because
      certain users may have two valid contracts active (e.g. one dependent
      and one employee).
    columns:
        - name: organization_name
          tests:
              - not_null
        - name: organization_id
          tests:
              - not_null
        - name: account_name
          tests:
              - not_null
        - name: account_id
          tests:
              - not_null
        - name: episode_id
              - not_null
    tests:
      - unique:
          column_name: "concat(episode_id, contract_id)"
