version: 2

models:
  - name: tableau_product_qa_bugs_daily
    columns:
        - name: date
          tests:
              - not_null

  - name: tableau_product_qa_incidents_detailed
    columns:
        - name: incident_id
          tests:
              - not_null
        - name: problem_id
          tests:
              - not_null
        - name: subject
          tests:
              - not_null
    tests:
      - dbt_utils.recency:
          field: reported_at
          datepart: day
          interval: 3
