
version: 2

models:
  - name: messaging_channels
    columns:
      - name: episode_id
        tests:
          - not_null
          - unique

      - name: user_id
        tests:
          - not_null
