
version: 2

models:
  - name: messaging_posts_patient_daily
    columns:
      - name: date_day
        tests:
          - not_null

      - name: user_id
        tests:
          - not_null

      - name: episode_id
        tests:
          - not_null
          - relationships:
              to: ref('messaging_channels')
              field: episode_id

      - name: post_count
        tests:
          - not_null

    tests:
      - unique:
          column_name: "concat(date_day, user_id, episode_id)"

      - dbt_utils.recency:
          field: date_day
          datepart: day
          interval: 2

  - name: messaging_posts_all_time
    description: a union of old mm_posts and new messaging_posts to combine
      data from the old ETL and the new; this is an incremental model with
      an index on created_at
    columns:
      - name: post_id
        tests:
          - not_null
          - unique

      - name: created_at
        tests:
          - not_null

      - name: episode_id
        tests:
          - not_null

      - name: is_internal_post
        tests:
          - not_null

    tests:
      - dbt_utils.recency:
          field: created_at
          datepart: hour
          interval: 24

  - name: messaging_channels
    columns:
        - name: episode_id
          tests:
              - unique
              - not_null
        - name: user_id
          tests:
              - not_null
    tests:
      - dbt_utils.recency:
          field: created_at
          datepart: hour
          interval: 24

  - name: messaging_posts_w_lag_detail
    description: messaging posts with detail about the previous message
      that was sent by another user; the previous message has a timestamp
      and user_type for calculating response times
    columns:
        - name: post_id
          tests:
              - not_null
              - unique
        - name: user_id
          tests:
              - not_null

  - name: messaging_practitioner_responses
    description: a subset of `messaging_posts_w_lag_detail` that includes only
      posts sent by a physician following a post by a patient; this is then
      joined into assigned time to calculate average response time to patients
      by practitioners
    columns:
        - name: post_id
          tests:
              - not_null
              - unique
        - name: date_day
          tests:
              - not_null
        - name: episode_id
          tests:
              - not_null
        - name: in_chat_time
          tests:
              - not_null
