version: 2

## TODO add more testing to these models

models:
  - name: funnel_sign_up_dob_match
    description: |
      a model for analyzing the steps of the DOB matched funnel
    columns:
      - name: user_id
        tests:
          - not_null

  - name: funnel_sign_up_no_dob_match
    description: |
      a model for analyzing the steps of the no DOB matched funnel
    columns:
      - name: user_id
        tests:
          - not_null

  - name: funnel_sign_up_employee_id
    description: |
      a model for analyzing the steps of the employee id funnel
    columns:
      - name: user_id
        tests:
          - not_null

  - name: funnel_sign_up_group_id
    description: |
      a model for analyzing the steps of the group id funnel
    columns:
      - name: user_id
        tests:
          - not_null

  - name: funnel_sign_up_need_help_exit
    description: |
      a model for analyzing who hit dob, email, and then need help
    columns:
      - name: user_id
        tests:
          - not_null

  - name: funnel_sign_up_dob_email_back_to_dob
    description: |
      a model for analyzing who went from dob to email and then back to dob

      note that this is not the general use case for a funnel (funnels should be
      DAGs) but will work if you filter on a nonzero time_delta_from_last_event
    columns:
      - name: user_id
        tests:
          - not_null

  - name: funnel_sign_up_dob_group_id_back_to_dob
    description: |
      a model for analyzing who went from dob to email and then back to dob

      note that this is not the general use case for a funnel (funnels should be
      DAGs) but will work if you filter on a nonzero time_delta_from_last_event
    columns:
      - name: user_id
        tests:
          - not_null
