
version: 2

models:

  - name: xero_expenses_detailed
    description: 'Xero expenses going in the P&L report with account grouping'

    columns:
      - name: account_group
        tests:
          - not_null
          - accepted_values:
              values: ['N/A', 'Sales Expenses', 'Customer Success',
              'General Administration', 'Health Team', 'Marketing Expenses',
              'Technology', 'New Services', 'Partnerships', 'Human Ressources']

      - name: account_budget_category
        tests:
          - not_null

  - name: xero_budget_monthly_detailed
    columns:
      - name: date_month
        tests:
          - not_null

      - name: account_budget_category
        tests:
          - not_null

      - name: amount
        tests:
          - not_null

      - name: budget_department
        tests:
          - not_null

    tests:
        - unique:
            column_name: "concat(date_month, account_budget_category)"
