
version: 2

models:
  - name: scribe_organizations_day
    description: |
      Table with one record per organization and per month after their billing
      start date

    columns:
      - name: date_day
        tests:
          - not_null

      - name: organization_id
        tests:
          - not_null

      - name: organization_name
        tests:
          - not_null

    tests:
      - unique:
          column_name: "concat(date_day, organization_id)"

  - name: scribe_organizations_monthly
    columns:
      - name: date_month
        tests:
          - not_null

      - name: organization_id
        tests:
          - not_null

      - name: organization_name
        tests:
          - not_null

      - name: active_contracts
        tests:
          - not_null

      - name: min_active_contracts
        tests:
          - not_null

      - name: max_active_contracts
        tests:
          - not_null

      - name: price_monthly
        tests:
          - not_null

    tests:
      - unique:
          column_name: "concat(date_month, organization_id)"
      - dbt_utils.recency:
          field: date_month
          datepart: month
          interval: 1

  - name: scribe_active_contracts_monthly
    columns:
      - name: date_month
        tests:
          - not_null
          - unique

      - name: active_contracts
        tests:
          - not_null

      - name: active_contracts_paid
        tests:
          - not_null

      - name: active_contracts_unpaid
        tests:
          - not_null

  - name: scribe_contracts_daily
    columns:
      - name: date_day
        tests:
          - not_null
          - unique

      - name: contract_count
        tests:
          - not_null

      - name: contract_paid_count
        tests:
          - not_null

  - name: scribe_contracts_weekly
    columns:
      - name: date_week
        tests:
          - not_null
          - unique

      - name: contract_count
        tests:
          - not_null

      - name: contract_paid_count
        tests:
          - not_null

  - name: scribe_organization_province_split
    description: |
      Ratio of signed up users per province by organization

    columns:
      - name: organization_id
        tests:
          - not_null
          - unique
      - name: quebec_perc
        tests:
          - not_null
      - name: ontario_perc
        tests:
          - not_null
      - name: prince_edward_island_perc
        tests:
          - not_null
      - name: alberta_perc
        tests:
          - not_null
      - name: ontario_perc
        tests:
          - not_null
      - name: british_columbia_perc
        tests:
          - not_null
      - name: saskatchewan_perc
        tests:
          - not_null
      - name: manitoba_perc
        tests:
          - not_null
      - name: quebec_perc
        tests:
          - not_null
      - name: nova_scotia_perc
        tests:
          - not_null
      - name: new_brunswick_perc
        tests:
          - not_null
      - name: newfoundland_and_labrador_perc
        tests:
          - not_null
      - name: yukon_perc
        tests:
          - not_null

  - name: scribe_organizations_daily
    description: |
      Number of daily active contracts by organization

    columns:
      - name: date_day
        tests:
          - not_null

      - name: organization_id
        tests:
          - not_null

      - name: active_contracts
        tests:
          - not_null

    tests:
      - unique:
          column_name: "concat(date_day, organization_id)"

  - name: scribe_organizations_weekly
    description: |
      Number of weekly active contracts by organization

    columns:
      - name: date_week
        tests:
          - not_null

      - name: organization_id
        tests:
          - not_null

      - name: active_contracts
        tests:
          - not_null

    tests:
      - unique:
          column_name: "concat(date_week, organization_id)"

  - name: scribe_organization_mrr_by_province_weekly
    description: |
      Estimated split of MRR by province by organization
      Estimate is based on percentage of signup by province per organization

    columns:
      - name: date_week
        tests:
          - not_null
      - name: mrr_quebec
        tests:
          - not_null
      - name: mrr_ontario
        tests:
          - not_null
      - name: mrr_prince_edward_island
        tests:
          - not_null
      - name: mrr_alberta
        tests:
          - not_null
      - name: mrr_ontario
        tests:
          - not_null
      - name: mrr_british_columbia
        tests:
          - not_null
      - name: mrr_saskatchewan
        tests:
          - not_null
      - name: mrr_manitoba
        tests:
          - not_null
      - name: mrr_quebec
        tests:
          - not_null
      - name: mrr_nova_scotia
        tests:
          - not_null
      - name: mrr_new_brunswick
        tests:
          - not_null
      - name: mrr_newfoundland_and_labrador
        tests:
          - not_null
      - name: mrr_yukon
        tests:
          - not_null

    tests:
      - unique:
          column_name: "concat(date_week, organization_id)"

  - name: scribe_organizations_active_today
    columns:
      - name: organization_id
        tests:
          - not_null
          - unique

      - name: organization_name
        tests:
          - not_null

      - name: email_preference
        tests:
          - not_null
          - accepted_values:
              values: ['english', 'french', 'bilingual-french-english',
                'bilingual-english-french']

      - name: is_paid
        tests:
          - not_null
