
version: 2

models:
  - name: scribe_contracts_detailed
    columns:
      - name: contract_id
        tests:
          - not_null
          - unique

      - name: during
        tests:
          - not_null

      - name: organization_id
        tests:
          - not_null

      - name: organization_name
        tests:
          - not_null

      - name: created
        tests:
          - not_null

      - name: plan_id
        tests:
          - not_null

      - name: participant_id
        tests:
          - not_null

      - name: charge_price
        tests:
          - not_null

      - name: charge_strategy
        tests:
          - not_null

      - name: billing_start_date
        tests:
          - not_null

      - name: is_paid
        tests:
          - not_null

      - name: admin_area_name
        tests:
          - not_null
          - accepted_values:
              values: ['Prince Edward Island', 'Alberta', 'Ontario',
              'Saskatchewan', 'British Columbia', 'Manitoba', 'Quebec',
              'New Brunswick', 'Nova Scotia', 'Yukon']

  - name: scribe_users_detailed
    columns:
      - name: user_id
        tests:
          - not_null
          - unique

      - name: created_at
        tests:
          - not_null

      - name: status
        tests:
          - not_null
          - accepted_values:
              values: ['future', 'deleted', 'deactivated',
              'registered', 'invited']

      - name: is_signed_up
        tests:
          - not_null

      - name: is_child
        tests:
          - not_null

  - name: scribe_organizations_detailed
    columns:
      - name: organization_id
        tests:
          - not_null
          - unique

      - name: organization_name
        tests:
          - not_null

      - name: billing_start_date
        tests:
          - not_null

      - name: is_paid
        tests:
          - not_null

      - name: charge_strategy
        tests:
          - not_null
          - accepted_values:
              values: ['free', 'auto_dynamic', 'dynamic', 'fixed']

      - name: charge_price
        tests:
          - not_null

      - name: province
        tests:
          - not_null
          - accepted_values:
              values: ['Prince Edward Island', 'Alberta', 'Ontario',
              'Saskatchewan', 'British Columbia', 'Manitoba', 'Quebec',
              'New Brunswick', 'Nova Scotia', 'Yukon']

  - name: scribe_user_contract_detailed
    columns:
      - name: contract_id
        tests:
          - not_null

      - name: user_id
        tests:
          - not_null

      - name: organization_id
        tests:
          - not_null

      - name: participant_id
        tests:
          - not_null

      - name: during
        tests:
          - not_null

      - name: organization_is_paid
        tests:
          - not_null

      - name: is_employee
        tests:
          - not_null

      - name: is_child
        tests:
          - not_null

      - name: family_member_type
        tests:
          - not_null
          - accepted_values:
              values: ['employee', 'child', 'dependent']

      - name: language
        tests:
          - not_null
          - accepted_values:
              values: ['fr', 'en']

      - name: residence_province
        tests:
          - not_null
          - accepted_values:
              values: ['Prince Edward Island', 'Alberta', 'Ontario',
              'Saskatchewan', 'British Columbia', 'Manitoba', 'Quebec',
              'New Brunswick', 'Nova Scotia', 'Yukon']

    tests:
      - unique:
          column_name: "concat(user_id, contract_id)"
