
version: 2

models:
  - name: scribe_contracts_detailed
    columns:
      - name: contract_id
        tests:
          - not_null
          - unique

      - name: during
        tests:
          - not_null

      - name: organization_id
        tests:
          - not_null

      - name: organization_name
        tests:
          - not_null

      - name: created
        tests:
          - not_null

      - name: plan_id
        tests:
          - not_null

      - name: participant_id
        tests:
          - not_null

      - name: charge_price
        tests:
          - not_null

      - name: charge_strategy
        tests:
          - not_null

      - name: billing_start_date
        tests:
          - not_null

      - name: is_paid
        tests:
          - not_null

  - name: scribe_organizations_detailed
    columns:
      - name: organization_id
        tests:
          - not_null
          - unique

      - name: organization_name
        tests:
          - not_null

      - name: billing_start_date
        tests:
          - not_null

      - name: is_paid
        tests:
          - not_null

      - name: charge_strategy
        tests:
          - not_null
          - accepted_values:
              values: ['free', 'auto_dynamic', 'dynamic', 'fixed']

      - name: charge_price
        tests:
          - not_null
