
version: 2

models:
  - name: intercom_conversations
    columns:
      - name: conversation_id
        tests:
          - not_null
          - unique
    tests:
      - dbt_utils.recency:
          field: updated_at
          datepart: hour
          interval: 72

  - name: intercom_conversation_parts
    columns:
      - name: conversation_id
        tests:
          - not_null
      - name: author_type
        tests:
          - not_null

  - name: intercom_users
    columns: 
      - name: intercom_user_id
        tests:
          - not_null
          - unique
