
version: 2

models:
  - name: wiw_locations
    description: |
      When I Work locations objects
    columns:
      - name: location_id
        tests:
          - not_null
          - unique
      - name: location_name
        tests:
          - not_null
          - unique

  - name: wiw_positions
    description: |
      When I Work position objects; each shift has a position
    columns:
      - name: position_id
        tests:
          - not_null
          - unique
      - name: position_name
        tests:
          - not_null

  - name: wiw_shifts
    description: |
      When I Work shifts objects; these are shifts without their details like
      position and location
    columns:
      - name: shift_id
        tests:
          - not_null
          - unique
      - name: location_id
        tests:
          - not_null
          - relationships:
                  to: ref('wiw_locations')
                  field: location_id
      - name: wiw_user_id
        tests:
          - not_null
          - relationships:
                  to: ref('wiw_users')
                  field: wiw_user_id

  - name: wiw_users
    description: |
      When I Work users objects; these are employees and contractors who can be
      scheduled for shifts
    columns:
      - name: wiw_user_id
        tests:
          - not_null
          - unique

  - name: wiw_users_snapshot_2018_09
    description: |
      Snapshot of WIW user hourly rates
      before GP were moved to pay per consult
    columns:
      - name: wiw_user_id
        tests:
          - not_null
          - unique

  - name: wiw_position_groups
    description: |
      Mapping of WIW position to care team roles
    columns:
      - name: position_name
        tests:
          - not_null
          - unique
      - name: position_group
        tests:
          - not_null
          - accepted_values:
              values: ['N/A', 'Nurse Clinician', 'Care Coordinator',
                'General Practitioner', 'Nurse Practitioner', 'Psychologist',
                'Nutritionist', 'Psychotherapist']
