version: 2

models:
  - name: github_deploys_daily
    columns:
        - name: merged_at_date
          tests:
              - unique
              - not_null
        - name: deploys_count
          tests:
              - not_null
