version: 2

models:
  - name: careplatform_pages_activity
    description: transformed page navigation events to be used later in
      tracking care team members' activity in the CP.
    columns:
      - name: activity
        tests:
          - not_null
      - name: user_id
        tests:
          - not_null
      - name: date_day_est
        tests:
          - not_null
      - name: timestamp
        tests:
          - not_null

  - name: careplatform_appointment_booking_started
    description: filtered template sent command for the appointment booking
      template
    columns:
      - name: episode_id
        tests:
          - not_null
      - name: user_id
        tests:
          - not_null
      - name: timestamp
        tests:
          - not_null

    tests:
      - unique:
          column_name: "concat(episode_id, timestamp)"

  - name: careplatform_outcome_set
    description: an event for every time the outcome is set on an episode with
      which outcome was set and by whom
    columns:
      - name: timestamp
        tests:
          - not_null
      - name: outcome
        tests:
          - not_null

    tests:
      - unique:
          column_name: "concat(episode_id, timestamp)"
