version: 2

models:
  - name: careplatform_pages_activity
    description: transformed page navigation events to be used later in
      tracking care team members' activity in the CP.
    columns:
      - name: activity
        tests:
          - not_null
      - name: user_id
        tests:
          - not_null
      - name: date_day_est
        tests:
          - not_null
      - name: timestamp
        tests:
          - not_null
