
version: 2

# TODO: rename all timestamps to timestamp and add tests

models:
  - name: careplatform_reminder_created
    columns:
      - name: episode_id
        tests:
          - not_null
      - name: timestamp
        tests:
          - not_null
    tests:
      - dbt_utils.recency:
          field: timestamp
          datepart: hour
          interval: 15

  - name: careplatform_reminders_status_updated
    columns:
      - name: episode_id
        tests:
          - not_null

  - name: careplatform_slash_command_triggered
    columns:
      - name: episode_id
        tests:
          - not_null

  - name: careplatform_video_stream_created
    columns:
      - name: episode_id
        tests:
          - not_null
      - name: timestamp
        tests:
          - not_null

  - name: careplatform_cp_video_session_remote_connected
    columns:
      - name: episode_id
        tests:
          - not_null
      - name: timestamp
        tests:
          - not_null

  - name: careplatform_video_stream_ended
    columns:
      - name: timestamp
        tests:
          - not_null

  - name: careplatform_message_retracted
    columns:
      - name: episode_id
        tests:
          - not_null
      - name: timestamp
        tests:
          - not_null

  - name: careplatform_note_created
    columns:
      - name: episode_id
        tests:
          - not_null
      - name: timestamp
        tests:
          - not_null

  - name: careplatform_electron_reload
    columns:
      - name: timestamp
        tests:
          - not_null

  - name: careplatform_family_doctor_added
    columns:
      - name: timestamp
        tests:
          - not_null

  - name: careplatform_family_doctor_updated
    columns:
      - name: timestamp
        tests:
          - not_null

  - name: careplatform_sidebar_clicked
    columns:
      - name: episode_id
        tests:
          - not_null
      - name: timestamp
        tests:
          - not_null

  - name: careplatform_pages
    columns:
      - name: timestamp
        tests:
          - not_null
      - name: user_id
        tests:
          - not_null
    tests:
      - unique:
          column_name: "concat(user_id, timestamp)"
