
version: 2

models:
  - name: salesforce_users_month
    description: |
      Table with one record per salesforce user between their creation date
      and their last login

  - name: salesforce_targets_monthly
    description: |
      For each AE and EAE active month, the table includes their target, taking
      ramp time into account and their actual close MRR.

  - name: salesforce_monthly_users_by_title
    description: |
      Number of users with a title that were active on this month

  - name: salesforce_opportunities_stalled_period
    description: |
      Opportunities that were put in the `Stalled` or `Long term` stage with the
      time range during which they where in this stage

  - name: salesforce_pipeline_monthly
    description: |
      Monthly opportunities in the pipeline

      An opportunity is in the pipeline for a given month if it was opened on
      the first day of the month.
      Stalled and long term opportunities are excluded from the pipeline for as
      long as they stay in these stages.

    columns:
      - name: is_first_month_in_pipeline
        description: |
          True if this month is the first month of the opp in the pipeline.

          The first month is the month right after the opportunity was added to
          the pipeline. So if an opportunity has a meeting on Feb. 20th, its
          first month in pipeline will be March.

  - name: salesforce_ltv
    columns:
      - name: date_month
        tests:
          - not_null

      - name: mrr_signed
        tests:
          - not_null

      - name: mrr_signed_eae
        tests:
          - not_null

      - name: mrr_signed_ae
        tests:
          - not_null

  - name: salesforce_pipeline_weighted_monthly
    columns:
      - name: amount
        tests:
          - not_null
      - name: amount_weighted
        description: |
          Weights calculated as the 3 months conversion rates of the 2
          quarters ago
      - name: amount_sf_weighted
        description: |
          Static weights used in the Salesforce weighted pipeline
      - name: segment_group
        tests:
          - not_null
      - name: stage_name_this_month
        tests:
          - not_null
          - accepted_values:
              values: ['Decide', 'Justify', 'Validate', 'Educate', 'Initiate',
                'Meeting Booked']
    tests:
      - unique:
          column_name: "concat(date_month, opportunity_id)"
      - dbt_utils.expression_is_true:
          expression: "segment_group = 'N/A' or amount_weighted is not null"

  - name: salesforce_new_services_won_weekly
    columns:
      - name: date_quarter
        tests:
          - not_null

      - name: date_week
        tests:
          - not_null
          - unique

      - name: mrr_stress_mgmt
        tests:
          - not_null

      - name: mrr_24_7
        tests:
          - not_null

  - name: salesforce_pipeline_probabilities
    columns:
      - name: date_quarter
        tests:
          - not_null
      - name: segment_group
        tests:
          - not_null
      - name: stage_name
        tests:
          - not_null
          - accepted_values:
              values: ['Meeting Booked', 'Initiate', 'Educate', 'Validate',
                'Justify', 'Decide']
    tests:
      - unique:
          column_name: "concat(date_quarter, segment_group, stage_name)"
