
version: 2

models:
  - name: delighted_nps_patient_survey
    columns:
      - name: email
        tests:
          - not_null

      - name: score
        tests:
          - not_null

      - name: category
        tests:
          - not_null

      - name: timestamp
        tests:
          - not_null

      - name: date_week
        tests:
          - not_null

      - name: date_month
        tests:
          - not_null

    tests:
      - dbt_utils.recency:
          field: timestamp
          datepart: hour
          interval: 24

  - name: delighted_nps_dm_survey
    columns:
      - name: email
        tests:
          - not_null

      - name: score
        tests:
          - not_null

      - name: category
        tests:
          - not_null

      - name: timestamp
        tests:
          - not_null
