version: 2

models:
  - name: countdown_qnaire_completion_stats

    columns:
        - name: qnaire
          tests:
              - not_null
        - name: started_at
          tests:
              - not_null
        - name: qnaire_tid
          tests:
              - not_null
              - unique

  - name: countdown_episode_started_sequence

    columns:
        - name: episode_id
          tests:
              - not_null
              - unique
