version: 2

models:
  - name: dxa_cc_classifier_data_not_validated
    description: pulls data from countdown with cc codes or not, answers to 
      question == ask_symptoms, only the ones that were not validated by 
      doctors yet.
    columns:
        - name: episode_id
          tests:
              - not_null
              - unique
        - name: descript
          tests:
              - not_null
        - name: replied_at
          tests:
              - not_null
  - name: dxa_cc_classifier_data_validated_labels
    description: model for testing cc codes are correct
    columns:
        - name: doctor_label
          tests:
            - not_null
  - name: data_dxa_cc_classifier_data_validated
    description: model from csv
    columns:
        - name: doctor_label
          tests:
            - not_null
