
version: 2

models:
  - name: nps_patient_survey_with_user_id
    columns:
      - name: user_id
        tests:
          - not_null

      - name: score
        tests:
          - not_null

      - name: category
        tests:
          - not_null
          - accepted_values:
              values: ['promoter', 'passive', 'detractor']

  - name: nps_dm_list
    columns:
      - name: email
        tests:
          - not_null
          - unique

      - name: contact_type
        tests:
          - not_null
          - accepted_values:
              values: ['HR + DM', 'Decision-Maker', 'HR Contact (User)']

      - name: organization_id
        tests:
          - not_null

      - name: month_since_billing_start_date
        tests:
          - not_null

      - name: locale
        tests:
          - not_null
          - accepted_values:
              values: ['en-dialogue-2', 'fr-dialogue-2']

      - name: delighted_email_subject
        tests:
          - not_null

      - name: delighted_intro_message
        tests:
          - not_null

  - name: nps_patient_list
    columns:
      - name: user_id
        tests:
          - not_null

      - name: email
        tests:
          - not_null

      - name: episode_id
        tests:
          - not_null
          - unique

      - name: locale
        tests:
          - not_null
          - accepted_values:
              values: ['en', 'fr']
