select id as account_id
	, name as account_name
	, coalesce(number_of_employees, number_of_employees_c) as number_of_employees
	, billing_city
	, dept_source_c
	, bs_account_status_c
	, bs_activity_status_c
	, bs_open_opportunities_c
	, insurance_carrier_c
	, preferred_rate_c
	, average_number_of_monthly_renewals_c
	, billing_country
	, monthly_price_per_employee_c
	, partner_broker_consultant_firm_c
	, billing_postal_code
	, last_activity_date
	, last_viewed_date
	, shipping_state
	, shipping_street
	, shipping_street_2_c
	, street_2_c
	, unionized_c
	, annual_revenue
	, billing_date_c
	, click_to_dial_click_to_call_skype_c
	, company_type_c
	, billing_street
	, sdr_c
	, total_partner_opportunities_mrr_c
	, bs_status_icon_c
	, client_churn_date_c
	, crunchbase_c
	, executive_sponsor_c
	, master_record_id
	, owner_id
	, owner_not_a_user_c
	, billing_state
	, commission_rate_c
	, created_by_id
	, created_date
	, data_quality_score_c
	, description
	, eap_c
	, last_modified_date
	, last_referenced_date
	, number_of_brokers_c
	, number_of_clients_c
	, click_to_dial_click_to_call_phone_c
	, fax
	, shipping_postal_code
	, summary_c
	, website
	, zisf_zoom_lastupdated_c
	, active_c
	, activity_icon_c
	, phone
	, total_closed_lives_c
	, linked_in_c
	, ownership
	, partner_broker_consultant_individual_c
	, referred_by_c
	, system_modstamp
	, target_account_c
	, type
	, zisf_zoom_info_industry_c
	, account_source
	, bs_lost_opportunities_c
	, client_start_date_c
	, industry
	, mrr_c::float as mrr
	, relationship_c
	, relationship_status_c
	, ticker_symbol
	, bs_won_opportunities_c
	, uuid_ts
	, account_executive_c
	, number_of_lives_c
	, of_open_cases_c
	, parent_id
	, partner_insurance_carrier_c
	, rating
	, record_type_id
	, shipping_city
	, bs_account_po_1_c
	, is_deleted
	, last_modified_by_id
	, lead_source_partner_c
	, photo_url
	, account_id_external_c
	, ae_c
	, bs_days_since_last_activity_c
	, cirrusadv_created_by_cirrus_insight_c
	, data_quality_description_c
	, shipping_country
	, tier_c
	, prospecting_status_c
	, days_in_current_status_c
	, last_prospect_status_change_date_c
	, rnw_date_c
	, churn_reason_details_c
	, churn_reason_c
	, latest_billing_start_date_c
	, cs_account_manager_c
	, zisf_zoom_info_complete_status_c
	, zisf_zoom_clean_status_c
	, shipping_country_code
	, billing_country_code
	, billing_state_code
	, shipping_state_code
	, broker_advisor_c
	, current_mrr_c
	, current_paying_employees_c
	, lf_visit_count_c
from salesforce.accounts
where not is_deleted
