select id
	, received_at
	, is_active
	, street
	, user_preferences_show_country_to_external_users
	, user_preferences_show_fax_to_external_users
	, call_center_id
	, company_name
	, default_group_notification_frequency
	, user_preferences_apex_pages_developer_mode
	, user_preferences_event_reminders_checkbox_default
	, user_preferences_disable_profile_post_email
	, receives_admin_info_emails
	, user_permissions_sfcontent_user
	, user_preferences_disable_all_feeds_email
	, user_preferences_disable_file_share_notifications_for_api
	, user_preferences_disable_later_comment_email
	, user_preferences_show_email_to_external_users
	, user_preferences_show_profile_pic_to_guest_users
	, user_preferences_show_street_address_to_external_users
	, community_nickname
	, case
		-- Celine's maternity leave date
		when id = '0056A000000j1k2QAA'
		then '2018-06-30'
		else last_login_date
	end as last_login_date
	, last_modified_date
	, user_role_id
	, user_preferences_show_city_to_guest_users
	, last_password_change_date
	, user_permissions_offline_user
	, user_preferences_show_fax_to_guest_users
	, user_preferences_show_country_to_guest_users
	, user_preferences_show_state_to_external_users
	, digest_frequency
	, last_modified_by_id
	, user_preferences_cache_diagnostics
	, user_preferences_show_postal_code_to_external_users
	, user_preferences_show_work_phone_to_guest_users
	, user_preferences_sort_feed_by_comment
	, email
	, profile_id
	, user_preferences_show_email_to_guest_users
	, user_permissions_mobile_user
	, user_preferences_hide_chatter_onboarding_splash
	, user_preferences_hide_lightning_migration_modal
	, user_preferences_show_state_to_guest_users
	, bs_users_po_1_c
	, forecast_enabled
	, phone
	, user_preferences_show_work_phone_to_external_users
	, user_preferences_disable_bookmark_email
	, user_preferences_disable_endorsement_email
	, user_preferences_preview_lightning
	, user_preferences_reminder_sound_off
	, user_preferences_show_title_to_guest_users
	, alias
	, name
	, user_permissions_avantgo_user
	, username
	, user_preferences_show_manager_to_external_users
	, full_photo_url
	, user_preferences_disable_followers_email
	, user_preferences_hide_csnget_chatter_mobile_task
	, user_permissions_support_user
	, user_preferences_disable_mentions_post_email
	, user_preferences_show_street_address_to_guest_users
	, city
	, last_referenced_date
	, title
	, user_permissions_interaction_user
	, last_viewed_date
	, mobile_phone
	, small_photo_url
	, state
	, user_permissions_call_center_auto_login
	, user_preferences_enable_auto_sub_for_feeds
	, about_me
	, created_date
	, postal_code
	, user_preferences_dis_comment_after_like_email
	, user_preferences_dis_prof_post_comment_email
	, user_preferences_global_nav_bar_wtshown
	, user_type
	, first_name
	, is_profile_photo_active
	, medium_banner_photo_url
	, user_preferences_lightning_experience_preferred
	, user_preferences_task_reminders_checkbox_default
	, created_by_id
	, user_preferences_activity_reminders_popup
	, user_preferences_disable_share_post_email
	, system_modstamp
	, email_preferences_auto_bcc
	, email_preferences_stay_in_touch_reminder
	, language_locale_key
	, user_preferences_hide_sfx_welcome_mat
	, uuid_ts
	, country
	, locale_sid_key
	, receives_info_emails
	, user_preferences_disable_message_email
	, user_preferences_hide_s1_browser_ui
	, user_preferences_show_postal_code_to_guest_users
	, delegated_approver_id
	, signature
	, user_preferences_disable_change_comment_email
	, user_preferences_show_manager_to_guest_users
	, user_preferences_show_title_to_external_users
	, banner_photo_url
	, last_name
	, user_preferences_global_nav_grid_menu_wtshown
	, department
	, user_preferences_hide_end_user_onboarding_assistant_modal
	, user_preferences_hide_second_chatter_onboarding_splash
	, user_preferences_hide_csndesktop_task
	, user_preferences_show_mobile_phone_to_external_users
	, user_permissions_marketing_user
	, user_preferences_dis_mentions_comment_email
	, user_preferences_hide_bigger_photo_callout
	, user_preferences_show_city_to_external_users
	, manager_id
	, time_zone_sid_key
	, user_preferences_favorites_wtshown
	, medium_photo_url
	, small_banner_photo_url
	, user_preferences_create_lexapps_wtshown
	, user_preferences_disable_like_email
	, user_preferences_path_assistant_collapsed
	, user_preferences_show_mobile_phone_to_guest_users
	, email_encoding_key
	, email_preferences_auto_bcc_stay_in_touch
	, pi_can_view_not_assigned_prospects_c
	, division
	, country_code
	, state_code
	, case
        when name = 'Jonathan Bolduc'
        then '2017-12-01'
        else created_date
      end as started_date
    , id as user_id
    , name as user_name
    , state_code as province
from salesforce.users
