
version: 2

models:
  - name: salesforce_tasks
    columns:
      - name: id
        tests:
          - unique
          - not_null
    tests:
      - dbt_utils.recency:
          field: created_date
          datepart: hour
          interval: 72

  - name: salesforce_accounts
    columns:
      - name: account_id
        tests:
          - unique
          - not_null

  - name: salesforce_users
    columns:
      - name: user_id
        tests:
          - unique
          - not_null

      - name: started_date
        tests:
          - not_null

  - name: salesforce_opportunities
    columns:
      - name: opportunity_id
        tests:
          - unique
          - not_null

      - name: revenue_type
        tests:
          - not_null

      - name: self_signup_no_touch
        tests:
          - not_null

      - name: segment
        tests:
          - not_null
          - accepted_values:
              values: ['N/A', '1-39', '40-99', '100-199',
              '200-499', '500-999', '1000+']

      - name: segment_group
        tests:
          - not_null
          - accepted_values:
              values: ['N/A', '1-99', '100-499', '500+']

      - name: value_period
        tests:
          - not_null
          - accepted_values:
              values: ['N/A', 'Monthly', 'One Time', 'Annual']

      - name: partner_influence
        tests:
          - not_null
          - accepted_values:
              values: ['N/A', 'Full involvement', 'No involvement',
                'Introduced', 'Meeting Booked']

      - name: channel
        tests:
          - not_null
          - accepted_values:
              values: ['Direct', 'Partner']

      - name: original_source
        tests:
          - not_null
          - accepted_values:
              values: ['N/A', 'Network Intro (investor, etc.)', 'Outbound',
                'Inbound', 'Partner (carrier, advisor/broker, etc.)']

      - name: partner_involvement
        tests:
          - not_null
          - accepted_values:
              values: ['N/A', 'High', 'Low', 'Full', 'None']

  - name: salesforce_products
    columns:
      - name: product_id
        tests:
          - unique
          - not_null

      - name: product_name
        tests:
          - unique
          - not_null
          - accepted_values:
              values: ['24/7', 'Stress Management & Well-Being',
                'Virtual Care', 'Vaccination Campaign', 'Family Plan',
                'Individual Plan', 'Pharmacogenetics', 'EHS basic care I',
                'EHS basic care II', 'EHS basic care III']

  - name: salesforce_scribe_organizations
    columns:
      - name: organization_id
        tests:
          - not_null
          - unique

      - name: organization_name
        tests:
          - not_null

      - name: account_id
        tests:
          - not_null

  - name: salesforce_scribe_organizations_detailed
    columns:
      - name: organization_id
        tests:
          - not_null
          - unique

      - name: organization_name
        tests:
          - not_null

      - name: account_id
        tests:
          - not_null

      - name: account_name
        tests:
          - not_null

      - name: account_industry
        tests:
          - not_null

  - name: salesforce_employment_start_dates
    description: |
      Sales rep employment start dates used to exclude ramp-up time
      from the LTV:CAC calculation

    columns:
      - name: user_id
        tests:
          - not_null
          - unique

      - name: start_date
        tests:
          - not_null

  - name: salesforce_inbound_lead_sources
    columns:
      - name: lead_source
        tests:
          - not_null
          - unique

  - name: salesforce_pipeline_probabilities_default
    description: |
      Default weighted pipeline probabilities used when no weights are
      available for a given opportunity

      Baseline set using conversion rates as of April 2019

    columns:
      - name: segment_group
        tests:
          - not_null
          - accepted_values:
              values: ['1-99', '100-499', '500+']
      - name: stage_name
        tests:
          - not_null
          - accepted_values:
              values: ["Meeting Booked", "Initiate", "Educate", "Validate",
                "Justify", "Decide"]
      - name: probability
        tests:
          - not_null
    tests:
      - unique:
          column_name: "concat(segment_group, stage_name)"
      - dbt_utils.expression_is_true:
          expression: "probability > 0 and probability < 1"
