
version: 2

models:
  - name: salesforce_accounts
    columns:
      - name: account_id
        tests:
          - unique
          - not_null

  - name: salesforce_users
    columns:
      - name: user_id
        tests:
          - unique
          - not_null

      - name: started_date
        tests:
          - not_null

  - name: salesforce_opportunities
    columns:
      - name: opportunity_id
        tests:
          - unique
          - not_null

      - name: revenue_type
        tests:
          - not_null

      - name: self_signup_no_touch
        tests:
          - not_null

      - name: segment
        tests:
          - not_null
          - accepted_values:
              values: ['N/A', '1-39', '40-99', '100-199',
              '200-499', '500-999', '1000+']

      - name: value_period
        tests:
          - not_null
          - accepted_values:
              values: ['N/A', 'Monthly', 'One Time', 'Annual']

  - name: salesforce_products
    columns:
      - name: product_id
        tests:
          - unique
          - not_null

      - name: product_name
          - unique
          - not_null

  - name: salesforce_opportunity_product
    columns:
      - name: product_id
        tests:
          - not_null

      - name: opportunity_id
        tests:
          - not_null

    tests:
      - unique:
          column_name: "concat(product_id, opportunity_id)"

  - name: salesforce_scribe_organizations
    columns:
      - name: organization_id
        tests:
          - not_null
          - unique

      - name: organization_name
        tests:
          - not_null

      - name: account_id
        tests:
          - not_null

  - name: salesforce_scribe_organizations_detailed
    columns:
      - name: organization_id
        tests:
          - not_null
          - unique

      - name: organization_name
        tests:
          - not_null

      - name: account_id
        tests:
          - not_null

      - name: account_name
        tests:
          - not_null

      - name: account_industry
        tests:
          - not_null
